//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCore.Translations.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is invalid or expired ähnelt.
        /// </summary>
        public static string access_token_expired {
            get {
                return ResourceManager.GetString("access_token_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user account is locked out ähnelt.
        /// </summary>
        public static string account_locked_out {
            get {
                return ResourceManager.GetString("account_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The API credentials are missing ähnelt.
        /// </summary>
        public static string api_credentials_missing {
            get {
                return ResourceManager.GetString("api_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument is invalid ähnelt.
        /// </summary>
        public static string argument_invalid {
            get {
                return ResourceManager.GetString("argument_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument is missing ähnelt.
        /// </summary>
        public static string argument_missing {
            get {
                return ResourceManager.GetString("argument_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The authorization authority for this service is currently not available. Your access credentials cannot be validated. Please try again later ähnelt.
        /// </summary>
        public static string authorization_authority_not_available {
            get {
                return ResourceManager.GetString("authorization_authority_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID contains invalid characters ähnelt.
        /// </summary>
        public static string client_id_invalid {
            get {
                return ResourceManager.GetString("client_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID is missing ähnelt.
        /// </summary>
        public static string client_id_missing {
            get {
                return ResourceManager.GetString("client_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID is too long ähnelt.
        /// </summary>
        public static string client_id_too_long {
            get {
                return ResourceManager.GetString("client_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret contains invalid characters ähnelt.
        /// </summary>
        public static string client_secret_invalid {
            get {
                return ResourceManager.GetString("client_secret_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret is missing ähnelt.
        /// </summary>
        public static string client_secret_missing {
            get {
                return ResourceManager.GetString("client_secret_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret is too long ähnelt.
        /// </summary>
        public static string client_secret_too_long {
            get {
                return ResourceManager.GetString("client_secret_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code contains invalid characters ähnelt.
        /// </summary>
        public static string code_invalid {
            get {
                return ResourceManager.GetString("code_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code is missing ähnelt.
        /// </summary>
        public static string code_missing {
            get {
                return ResourceManager.GetString("code_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code is too long ähnelt.
        /// </summary>
        public static string code_too_long {
            get {
                return ResourceManager.GetString("code_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cookie is invalid or expired ähnelt.
        /// </summary>
        public static string cookie_invalid_or_expired {
            get {
                return ResourceManager.GetString("cookie_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This user name already exists ähnelt.
        /// </summary>
        public static string duplicate_user_name {
            get {
                return ResourceManager.GetString("duplicate_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is invalid ähnelt.
        /// </summary>
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is missing ähnelt.
        /// </summary>
        public static string email_missing {
            get {
                return ResourceManager.GetString("email_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected server error occured ähnelt.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user credentials are not valid ähnelt.
        /// </summary>
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is invalid ähnelt.
        /// </summary>
        public static string issuer_invalid {
            get {
                return ResourceManager.GetString("issuer_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is missing ähnelt.
        /// </summary>
        public static string issuer_missing {
            get {
                return ResourceManager.GetString("issuer_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is too long ähnelt.
        /// </summary>
        public static string issuer_too_long {
            get {
                return ResourceManager.GetString("issuer_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging limit must not exceed 50 records ähnelt.
        /// </summary>
        public static string max_paging_limit_exceeded {
            get {
                return ResourceManager.GetString("max_paging_limit_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging offset must not exceed 500 records ähnelt.
        /// </summary>
        public static string max_paging_offset_exceeded {
            get {
                return ResourceManager.GetString("max_paging_offset_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name contains invalid characters ähnelt.
        /// </summary>
        public static string name_invalid {
            get {
                return ResourceManager.GetString("name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name is missing ähnelt.
        /// </summary>
        public static string name_missing {
            get {
                return ResourceManager.GetString("name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name is too long ähnelt.
        /// </summary>
        public static string name_too_long {
            get {
                return ResourceManager.GetString("name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide records for the update operation ähnelt.
        /// </summary>
        public static string no_records_specified {
            get {
                return ResourceManager.GetString("no_records_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The record was not found ähnelt.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This functionality is not yet implemented ähnelt.
        /// </summary>
        public static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging limit must be equal to or greater than zero ähnelt.
        /// </summary>
        public static string paging_limit_invalid {
            get {
                return ResourceManager.GetString("paging_limit_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging offset must be equal to or greater than zero ähnelt.
        /// </summary>
        public static string paging_offset_invalid {
            get {
                return ResourceManager.GetString("paging_offset_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password confirmation is missing ähnelt.
        /// </summary>
        public static string password_confirmation_missing {
            get {
                return ResourceManager.GetString("password_confirmation_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password confirmation is not matching the password ähnelt.
        /// </summary>
        public static string password_confirmation_no_match {
            get {
                return ResourceManager.GetString("password_confirmation_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password does not match our records ähnelt.
        /// </summary>
        public static string password_does_not_match {
            get {
                return ResourceManager.GetString("password_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password contains invalid characters ähnelt.
        /// </summary>
        public static string password_invalid {
            get {
                return ResourceManager.GetString("password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is missing ähnelt.
        /// </summary>
        public static string password_missing {
            get {
                return ResourceManager.GetString("password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password requires non alphanumeric characters ähnelt.
        /// </summary>
        public static string password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is too long ähnelt.
        /// </summary>
        public static string password_too_long {
            get {
                return ResourceManager.GetString("password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is too short ähnelt.
        /// </summary>
        public static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The permission to access this location was denied ähnelt.
        /// </summary>
        public static string permission_denied {
            get {
                return ResourceManager.GetString("permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The phone number is invalid ähnelt.
        /// </summary>
        public static string phone_number_invalid {
            get {
                return ResourceManager.GetString("phone_number_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The phone number is missing ähnelt.
        /// </summary>
        public static string phone_number_missing {
            get {
                return ResourceManager.GetString("phone_number_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is invalid, decoding failed ähnelt.
        /// </summary>
        public static string private_key_invalid {
            get {
                return ResourceManager.GetString("private_key_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is missing ähnelt.
        /// </summary>
        public static string private_key_missing {
            get {
                return ResourceManager.GetString("private_key_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key string contains no private key delimiters ähnelt.
        /// </summary>
        public static string private_key_no_delimiters {
            get {
                return ResourceManager.GetString("private_key_no_delimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key data given does not contain private key data ähnelt.
        /// </summary>
        public static string private_key_no_private_key {
            get {
                return ResourceManager.GetString("private_key_no_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is too long ähnelt.
        /// </summary>
        public static string private_key_too_long {
            get {
                return ResourceManager.GetString("private_key_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is invalid ähnelt.
        /// </summary>
        public static string redirect_url_invalid {
            get {
                return ResourceManager.GetString("redirect_url_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is missing ähnelt.
        /// </summary>
        public static string redirect_url_missing {
            get {
                return ResourceManager.GetString("redirect_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL must be absolute ähnelt.
        /// </summary>
        public static string redirect_url_must_be_absolute {
            get {
                return ResourceManager.GetString("redirect_url_must_be_absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is not required ähnelt.
        /// </summary>
        public static string redirect_url_not_required {
            get {
                return ResourceManager.GetString("redirect_url_not_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is too long ähnelt.
        /// </summary>
        public static string redirect_url_too_long {
            get {
                return ResourceManager.GetString("redirect_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scroll UUID contains invalid characters ähnelt.
        /// </summary>
        public static string scroll_uuid_invalid {
            get {
                return ResourceManager.GetString("scroll_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scroll UUID is too long ähnelt.
        /// </summary>
        public static string scroll_uuid_too_long {
            get {
                return ResourceManager.GetString("scroll_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The security token is invalid or expired ähnelt.
        /// </summary>
        public static string security_token_invalid {
            get {
                return ResourceManager.GetString("security_token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state is invalid ähnelt.
        /// </summary>
        public static string state_invalid {
            get {
                return ResourceManager.GetString("state_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is invalid ähnelt.
        /// </summary>
        public static string subject_invalid {
            get {
                return ResourceManager.GetString("subject_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is missing ähnelt.
        /// </summary>
        public static string subject_missing {
            get {
                return ResourceManager.GetString("subject_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is too long ähnelt.
        /// </summary>
        public static string subject_too_long {
            get {
                return ResourceManager.GetString("subject_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant was not found ähnelt.
        /// </summary>
        public static string tenant_not_found {
            get {
                return ResourceManager.GetString("tenant_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is invalid or expired ähnelt.
        /// </summary>
        public static string token_invalid_or_expired {
            get {
                return ResourceManager.GetString("token_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please only update up to 50 records at once ähnelt.
        /// </summary>
        public static string too_many_update_records {
            get {
                return ResourceManager.GetString("too_many_update_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user credentials are missing ähnelt.
        /// </summary>
        public static string user_credentials_missing {
            get {
                return ResourceManager.GetString("user_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group was not found ähnelt.
        /// </summary>
        public static string user_group_not_found {
            get {
                return ResourceManager.GetString("user_group_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group UUID is invalid ähnelt.
        /// </summary>
        public static string user_group_uuid_invalid {
            get {
                return ResourceManager.GetString("user_group_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group UUID is missing ähnelt.
        /// </summary>
        public static string user_group_uuid_missing {
            get {
                return ResourceManager.GetString("user_group_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name contains invalid characters ähnelt.
        /// </summary>
        public static string user_name_invalid {
            get {
                return ResourceManager.GetString("user_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name is missing ähnelt.
        /// </summary>
        public static string user_name_missing {
            get {
                return ResourceManager.GetString("user_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name is too long ähnelt.
        /// </summary>
        public static string user_name_too_long {
            get {
                return ResourceManager.GetString("user_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user is no member of the user group ähnelt.
        /// </summary>
        public static string user_no_member_of_user_group {
            get {
                return ResourceManager.GetString("user_no_member_of_user_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user was not found ähnelt.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user UUID is invalid ähnelt.
        /// </summary>
        public static string user_uuid_invalid {
            get {
                return ResourceManager.GetString("user_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user UUID is missing ähnelt.
        /// </summary>
        public static string user_uuid_missing {
            get {
                return ResourceManager.GetString("user_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UUID is invalid ähnelt.
        /// </summary>
        public static string uuid_invalid {
            get {
                return ResourceManager.GetString("uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UUID is missing ähnelt.
        /// </summary>
        public static string uuid_missing {
            get {
                return ResourceManager.GetString("uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation of the submitted data failed ähnelt.
        /// </summary>
        public static string validation_failed {
            get {
                return ResourceManager.GetString("validation_failed", resourceCulture);
            }
        }
    }
}
