//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCore.Translations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is invalid or expired.
        /// </summary>
        public static string access_token_expired {
            get {
                return ResourceManager.GetString("access_token_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is missing.
        /// </summary>
        public static string access_token_missing {
            get {
                return ResourceManager.GetString("access_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is too long.
        /// </summary>
        public static string access_token_too_long {
            get {
                return ResourceManager.GetString("access_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed, because the user account is externally managed.
        /// </summary>
        public static string account_is_externally_managed {
            get {
                return ResourceManager.GetString("account_is_externally_managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account is locked out.
        /// </summary>
        public static string account_locked_out {
            get {
                return ResourceManager.GetString("account_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed, because the user groups and accounts are externally managed.
        /// </summary>
        public static string accounts_are_externally_managed {
            get {
                return ResourceManager.GetString("accounts_are_externally_managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address line 1 is missing.
        /// </summary>
        public static string address_line_1_missing {
            get {
                return ResourceManager.GetString("address_line_1_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address line 1 is too long.
        /// </summary>
        public static string address_line_1_too_long {
            get {
                return ResourceManager.GetString("address_line_1_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address line 2 is missing.
        /// </summary>
        public static string address_line_2_missing {
            get {
                return ResourceManager.GetString("address_line_2_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address line 2 is too long.
        /// </summary>
        public static string address_line_2_too_long {
            get {
                return ResourceManager.GetString("address_line_2_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API credentials are missing.
        /// </summary>
        public static string api_credentials_missing {
            get {
                return ResourceManager.GetString("api_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is invalid.
        /// </summary>
        public static string argument_invalid {
            get {
                return ResourceManager.GetString("argument_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is missing.
        /// </summary>
        public static string argument_missing {
            get {
                return ResourceManager.GetString("argument_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization authority for this service is currently not available. Your access credentials cannot be validated. Please try again later.
        /// </summary>
        public static string authorization_authority_not_available {
            get {
                return ResourceManager.GetString("authorization_authority_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {name} backend service is currently not available.
        /// </summary>
        public static string backend_service_not_available {
            get {
                return ResourceManager.GetString("backend_service_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The billing type is invalid.
        /// </summary>
        public static string billing_type_invalid {
            get {
                return ResourceManager.GetString("billing_type_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cancellation reason is missing.
        /// </summary>
        public static string cancellation_reason_missing {
            get {
                return ResourceManager.GetString("cancellation_reason_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cancellation reason is too long.
        /// </summary>
        public static string cancellation_reason_too_long {
            get {
                return ResourceManager.GetString("cancellation_reason_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System user groups must contain at least one member.
        /// </summary>
        public static string cannot_delete_last_system_user_group_member {
            get {
                return ResourceManager.GetString("cannot_delete_last_system_user_group_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is missing.
        /// </summary>
        public static string city_missing {
            get {
                return ResourceManager.GetString("city_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is too long.
        /// </summary>
        public static string city_too_long {
            get {
                return ResourceManager.GetString("city_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is assigned to more than 150 groups, which is not supported by Azure AD. Please either limit the amount of user groups assigned to the user, or use application roles.
        /// </summary>
        public static string claims_principal_has_too_many_groups {
            get {
                return ResourceManager.GetString("claims_principal_has_too_many_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client ID contains invalid characters.
        /// </summary>
        public static string client_id_invalid {
            get {
                return ResourceManager.GetString("client_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client ID is missing.
        /// </summary>
        public static string client_id_missing {
            get {
                return ResourceManager.GetString("client_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client ID is too long.
        /// </summary>
        public static string client_id_too_long {
            get {
                return ResourceManager.GetString("client_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client secret contains invalid characters.
        /// </summary>
        public static string client_secret_invalid {
            get {
                return ResourceManager.GetString("client_secret_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client secret is missing.
        /// </summary>
        public static string client_secret_missing {
            get {
                return ResourceManager.GetString("client_secret_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client secret is too long.
        /// </summary>
        public static string client_secret_too_long {
            get {
                return ResourceManager.GetString("client_secret_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the file was denied.
        /// </summary>
        public static string cloud_storage_file_access_denied {
            get {
                return ResourceManager.GetString("cloud_storage_file_access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found.
        /// </summary>
        public static string cloud_storage_file_not_found {
            get {
                return ResourceManager.GetString("cloud_storage_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code contains invalid characters.
        /// </summary>
        public static string code_invalid {
            get {
                return ResourceManager.GetString("code_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is missing.
        /// </summary>
        public static string code_missing {
            get {
                return ResourceManager.GetString("code_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is too long.
        /// </summary>
        public static string code_too_long {
            get {
                return ResourceManager.GetString("code_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is too long.
        /// </summary>
        public static string comment_too_long {
            get {
                return ResourceManager.GetString("comment_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation ID is missing.
        /// </summary>
        public static string confirmation_id_missing {
            get {
                return ResourceManager.GetString("confirmation_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation ID is too long.
        /// </summary>
        public static string confirmation_id_too_long {
            get {
                return ResourceManager.GetString("confirmation_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact person name is missing.
        /// </summary>
        public static string contact_person_name_missing {
            get {
                return ResourceManager.GetString("contact_person_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact person name is too long.
        /// </summary>
        public static string contact_person_name_too_long {
            get {
                return ResourceManager.GetString("contact_person_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The continuation UUID is invalid.
        /// </summary>
        public static string continuation_uuid_invalid {
            get {
                return ResourceManager.GetString("continuation_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cookie is invalid or expired.
        /// </summary>
        public static string cookie_invalid_or_expired {
            get {
                return ResourceManager.GetString("cookie_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is invalid.
        /// </summary>
        public static string culture_invalid {
            get {
                return ResourceManager.GetString("culture_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is missing.
        /// </summary>
        public static string culture_missing {
            get {
                return ResourceManager.GetString("culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is too long.
        /// </summary>
        public static string culture_too_long {
            get {
                return ResourceManager.GetString("culture_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency is invalid.
        /// </summary>
        public static string currency_invalid {
            get {
                return ResourceManager.GetString("currency_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency is missing.
        /// </summary>
        public static string currency_missing {
            get {
                return ResourceManager.GetString("currency_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language is missing.
        /// </summary>
        public static string default_culture_missing {
            get {
                return ResourceManager.GetString("default_culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default currency is invalid.
        /// </summary>
        public static string default_currency_invalid {
            get {
                return ResourceManager.GetString("default_currency_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default currency is missing.
        /// </summary>
        public static string default_currency_missing {
            get {
                return ResourceManager.GetString("default_currency_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is too long.
        /// </summary>
        public static string description_too_long {
            get {
                return ResourceManager.GetString("description_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The developer was not found.
        /// </summary>
        public static string developer_not_found {
            get {
                return ResourceManager.GetString("developer_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user name already exists.
        /// </summary>
        public static string duplicate_user_name {
            get {
                return ResourceManager.GetString("duplicate_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address for this user account has already been confirmed.
        /// </summary>
        public static string email_already_confirmed {
            get {
                return ResourceManager.GetString("email_already_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account with that email address already exists.
        /// </summary>
        public static string email_already_exists {
            get {
                return ResourceManager.GetString("email_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is missing.
        /// </summary>
        public static string email_missing {
            get {
                return ResourceManager.GetString("email_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not yet confirmed.
        /// </summary>
        public static string email_not_confirmed {
            get {
                return ResourceManager.GetString("email_not_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address does not exist.
        /// </summary>
        public static string email_not_existing {
            get {
                return ResourceManager.GetString("email_not_existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is too long.
        /// </summary>
        public static string email_too_long {
            get {
                return ResourceManager.GetString("email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured.
        /// </summary>
        public static string error_header {
            get {
                return ResourceManager.GetString("error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, but an unexpected error occured while processing your request..
        /// </summary>
        public static string error_header_text {
            get {
                return ResourceManager.GetString("error_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error message is invalid.
        /// </summary>
        public static string error_message_is_invalid {
            get {
                return ResourceManager.GetString("error_message_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request ID is:.
        /// </summary>
        public static string error_request_id {
            get {
                return ResourceManager.GetString("error_request_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external user group mapping contains invalid characters.
        /// </summary>
        public static string external_user_group_identifier_invalid {
            get {
                return ResourceManager.GetString("external_user_group_identifier_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external user group mapping is too long.
        /// </summary>
        public static string external_user_group_identifier_too_long {
            get {
                return ResourceManager.GetString("external_user_group_identifier_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external user ID is missing.
        /// </summary>
        public static string external_user_id_is_missing {
            get {
                return ResourceManager.GetString("external_user_id_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external user was not found.
        /// </summary>
        public static string external_user_not_found {
            get {
                return ResourceManager.GetString("external_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name contains invalid characters.
        /// </summary>
        public static string first_name_invalid {
            get {
                return ResourceManager.GetString("first_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is missing.
        /// </summary>
        public static string first_name_missing {
            get {
                return ResourceManager.GetString("first_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is too long.
        /// </summary>
        public static string first_name_too_long {
            get {
                return ResourceManager.GetString("first_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon ICO URL is missing.
        /// </summary>
        public static string icon_ico_url_missing {
            get {
                return ResourceManager.GetString("icon_ico_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon ICO URL is too long.
        /// </summary>
        public static string icon_ico_url_too_long {
            get {
                return ResourceManager.GetString("icon_ico_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity token is missing.
        /// </summary>
        public static string identity_token_missing {
            get {
                return ResourceManager.GetString("identity_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity token is too long.
        /// </summary>
        public static string identity_token_too_long {
            get {
                return ResourceManager.GetString("identity_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected server error occured.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user credentials are not valid.
        /// </summary>
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issuer is invalid.
        /// </summary>
        public static string issuer_invalid {
            get {
                return ResourceManager.GetString("issuer_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issuer is missing.
        /// </summary>
        public static string issuer_missing {
            get {
                return ResourceManager.GetString("issuer_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issuer is too long.
        /// </summary>
        public static string issuer_too_long {
            get {
                return ResourceManager.GetString("issuer_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 1 contains invalid characters.
        /// </summary>
        public static string key_1_invalid {
            get {
                return ResourceManager.GetString("key_1_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 1 is missing.
        /// </summary>
        public static string key_1_missing {
            get {
                return ResourceManager.GetString("key_1_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 1 is too long.
        /// </summary>
        public static string key_1_too_long {
            get {
                return ResourceManager.GetString("key_1_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 2 contains invalid characters.
        /// </summary>
        public static string key_2_invalid {
            get {
                return ResourceManager.GetString("key_2_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 2 is missing.
        /// </summary>
        public static string key_2_missing {
            get {
                return ResourceManager.GetString("key_2_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 2 is too long.
        /// </summary>
        public static string key_2_too_long {
            get {
                return ResourceManager.GetString("key_2_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 3 contains invalid characters.
        /// </summary>
        public static string key_3_invalid {
            get {
                return ResourceManager.GetString("key_3_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 3 is missing.
        /// </summary>
        public static string key_3_missing {
            get {
                return ResourceManager.GetString("key_3_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 3 is too long.
        /// </summary>
        public static string key_3_too_long {
            get {
                return ResourceManager.GetString("key_3_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 4 contains invalid characters.
        /// </summary>
        public static string key_4_invalid {
            get {
                return ResourceManager.GetString("key_4_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 4 is missing.
        /// </summary>
        public static string key_4_missing {
            get {
                return ResourceManager.GetString("key_4_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key 4 is too long.
        /// </summary>
        public static string key_4_too_long {
            get {
                return ResourceManager.GetString("key_4_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name contains invalid characters.
        /// </summary>
        public static string last_name_invalid {
            get {
                return ResourceManager.GetString("last_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is missing.
        /// </summary>
        public static string last_name_missing {
            get {
                return ResourceManager.GetString("last_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is too long.
        /// </summary>
        public static string last_name_too_long {
            get {
                return ResourceManager.GetString("last_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last updated at from value is invalid.
        /// </summary>
        public static string last_updated_at_from_invalid {
            get {
                return ResourceManager.GetString("last_updated_at_from_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last updated at to date is set to a date before the last updated at date.
        /// </summary>
        public static string last_updated_at_to_before_last_updated_at_from {
            get {
                return ResourceManager.GetString("last_updated_at_to_before_last_updated_at_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last updated at to value is invalid.
        /// </summary>
        public static string last_updated_at_to_invalid {
            get {
                return ResourceManager.GetString("last_updated_at_to_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link is expired or invalid.
        /// </summary>
        public static string link_invalid {
            get {
                return ResourceManager.GetString("link_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo PNG URL is missing.
        /// </summary>
        public static string logo_png_url_missing {
            get {
                return ResourceManager.GetString("logo_png_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo PNG URL is too long.
        /// </summary>
        public static string logo_png_url_too_long {
            get {
                return ResourceManager.GetString("logo_png_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo SVG URL is missing.
        /// </summary>
        public static string logo_svg_url_missing {
            get {
                return ResourceManager.GetString("logo_svg_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo SVG URL is too long.
        /// </summary>
        public static string logo_svg_url_too_long {
            get {
                return ResourceManager.GetString("logo_svg_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paging limit must not exceed 50 records.
        /// </summary>
        public static string max_paging_limit_exceeded {
            get {
                return ResourceManager.GetString("max_paging_limit_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paging offset must not exceed 5000 records.
        /// </summary>
        public static string max_paging_offset_exceeded {
            get {
                return ResourceManager.GetString("max_paging_offset_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name contains invalid characters.
        /// </summary>
        public static string name_invalid {
            get {
                return ResourceManager.GetString("name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is missing.
        /// </summary>
        public static string name_missing {
            get {
                return ResourceManager.GetString("name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long.
        /// </summary>
        public static string name_too_long {
            get {
                return ResourceManager.GetString("name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is missing.
        /// </summary>
        public static string new_password_missing {
            get {
                return ResourceManager.GetString("new_password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not use an disposable email address.
        /// </summary>
        public static string no_disposable_emails_allowed {
            get {
                return ResourceManager.GetString("no_disposable_emails_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide records for the update operation.
        /// </summary>
        public static string no_records_specified {
            get {
                return ResourceManager.GetString("no_records_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The no reply email display name is invalid.
        /// </summary>
        public static string noreply_email_display_name_invalid {
            get {
                return ResourceManager.GetString("noreply_email_display_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The no reply email display name is too long.
        /// </summary>
        public static string noreply_email_display_name_too_long {
            get {
                return ResourceManager.GetString("noreply_email_display_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The no reply email address is invalid.
        /// </summary>
        public static string noreply_email_invalid {
            get {
                return ResourceManager.GetString("noreply_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The no reply email address is too long.
        /// </summary>
        public static string noreply_email_too_long {
            get {
                return ResourceManager.GetString("noreply_email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not yet implemented.
        /// </summary>
        public static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification culture is invalid.
        /// </summary>
        public static string notification_culture_invalid {
            get {
                return ResourceManager.GetString("notification_culture_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification language is missing.
        /// </summary>
        public static string notification_culture_missing {
            get {
                return ResourceManager.GetString("notification_culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification UUID is invalid.
        /// </summary>
        public static string notification_uuid_invalid {
            get {
                return ResourceManager.GetString("notification_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification UUID is missing.
        /// </summary>
        public static string notification_uuid_missing {
            get {
                return ResourceManager.GetString("notification_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is missing.
        /// </summary>
        public static string old_password_missing {
            get {
                return ResourceManager.GetString("old_password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element was modified by another user, please try again.
        /// </summary>
        public static string optimistic_lock_violated {
            get {
                return ResourceManager.GetString("optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order ID is missing.
        /// </summary>
        public static string order_id_missing {
            get {
                return ResourceManager.GetString("order_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order ID is too long.
        /// </summary>
        public static string order_id_too_long {
            get {
                return ResourceManager.GetString("order_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name is invalid.
        /// </summary>
        public static string organization_invalid {
            get {
                return ResourceManager.GetString("organization_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name is missing.
        /// </summary>
        public static string organization_missing {
            get {
                return ResourceManager.GetString("organization_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name is too long.
        /// </summary>
        public static string organization_too_long {
            get {
                return ResourceManager.GetString("organization_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page was not found.
        /// </summary>
        public static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paging limit must be equal to or greater than zero.
        /// </summary>
        public static string paging_limit_invalid {
            get {
                return ResourceManager.GetString("paging_limit_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paging offset must be equal to or greater than zero.
        /// </summary>
        public static string paging_offset_invalid {
            get {
                return ResourceManager.GetString("paging_offset_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation is missing.
        /// </summary>
        public static string password_confirmation_missing {
            get {
                return ResourceManager.GetString("password_confirmation_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation is not matching the password.
        /// </summary>
        public static string password_confirmation_no_match {
            get {
                return ResourceManager.GetString("password_confirmation_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not match our records.
        /// </summary>
        public static string password_does_not_match {
            get {
                return ResourceManager.GetString("password_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is missing.
        /// </summary>
        public static string password_missing {
            get {
                return ResourceManager.GetString("password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires at least one digit.
        /// </summary>
        public static string password_requires_digit {
            get {
                return ResourceManager.GetString("password_requires_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires non alphanumeric characters.
        /// </summary>
        public static string password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too long.
        /// </summary>
        public static string password_too_long {
            get {
                return ResourceManager.GetString("password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short.
        /// </summary>
        public static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission to access this location was denied.
        /// </summary>
        public static string permission_denied {
            get {
                return ResourceManager.GetString("permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid.
        /// </summary>
        public static string phone_number_invalid {
            get {
                return ResourceManager.GetString("phone_number_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is missing.
        /// </summary>
        public static string phone_number_missing {
            get {
                return ResourceManager.GetString("phone_number_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is too long.
        /// </summary>
        public static string phone_number_too_long {
            get {
                return ResourceManager.GetString("phone_number_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept our Privacy Policy.
        /// </summary>
        public static string please_accept_privacy_policy {
            get {
                return ResourceManager.GetString("please_accept_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept our Terms and Conditions.
        /// </summary>
        public static string please_accept_terms_and_conditions {
            get {
                return ResourceManager.GetString("please_accept_terms_and_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code is missing.
        /// </summary>
        public static string postal_code_missing {
            get {
                return ResourceManager.GetString("postal_code_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code is too long.
        /// </summary>
        public static string postal_code_too_long {
            get {
                return ResourceManager.GetString("postal_code_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary color is invalid.
        /// </summary>
        public static string primary_color_invalid {
            get {
                return ResourceManager.GetString("primary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is invalid, decoding failed.
        /// </summary>
        public static string private_key_invalid {
            get {
                return ResourceManager.GetString("private_key_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is missing.
        /// </summary>
        public static string private_key_missing {
            get {
                return ResourceManager.GetString("private_key_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key string contains no private key delimiters.
        /// </summary>
        public static string private_key_no_delimiters {
            get {
                return ResourceManager.GetString("private_key_no_delimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key data given does not contain private key data.
        /// </summary>
        public static string private_key_no_private_key {
            get {
                return ResourceManager.GetString("private_key_no_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is too long.
        /// </summary>
        public static string private_key_too_long {
            get {
                return ResourceManager.GetString("private_key_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, Google reCAPTCHA failed to validate that you are no robot.
        /// </summary>
        public static string recaptcha_validation_failed {
            get {
                return ResourceManager.GetString("recaptcha_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL is invalid.
        /// </summary>
        public static string redirect_url_invalid {
            get {
                return ResourceManager.GetString("redirect_url_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL is missing.
        /// </summary>
        public static string redirect_url_missing {
            get {
                return ResourceManager.GetString("redirect_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL must be absolute.
        /// </summary>
        public static string redirect_url_must_be_absolute {
            get {
                return ResourceManager.GetString("redirect_url_must_be_absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL is not required.
        /// </summary>
        public static string redirect_url_not_required {
            get {
                return ResourceManager.GetString("redirect_url_not_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL is too long.
        /// </summary>
        public static string redirect_url_too_long {
            get {
                return ResourceManager.GetString("redirect_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is missing.
        /// </summary>
        public static string refresh_token_missing {
            get {
                return ResourceManager.GetString("refresh_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is too long.
        /// </summary>
        public static string refresh_token_too_long {
            get {
                return ResourceManager.GetString("refresh_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rejection reason is too long.
        /// </summary>
        public static string rejection_reason_too_long {
            get {
                return ResourceManager.GetString("rejection_reason_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scoped tenant UUID is invalid.
        /// </summary>
        public static string scoped_tenant_uuid_invalid {
            get {
                return ResourceManager.GetString("scoped_tenant_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scoped tenant UUID is missing.
        /// </summary>
        public static string scoped_tenant_uuid_missing {
            get {
                return ResourceManager.GetString("scoped_tenant_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scroll UUID contains invalid characters.
        /// </summary>
        public static string scroll_uuid_invalid {
            get {
                return ResourceManager.GetString("scroll_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scroll UUID is too long.
        /// </summary>
        public static string scroll_uuid_too_long {
            get {
                return ResourceManager.GetString("scroll_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search term is invalid.
        /// </summary>
        public static string search_term_invalid {
            get {
                return ResourceManager.GetString("search_term_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search term is too long.
        /// </summary>
        public static string search_term_loo_long {
            get {
                return ResourceManager.GetString("search_term_loo_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search term is missing.
        /// </summary>
        public static string search_term_missing {
            get {
                return ResourceManager.GetString("search_term_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secondary color is invalid.
        /// </summary>
        public static string secondary_color_invalid {
            get {
                return ResourceManager.GetString("secondary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security token is invalid or expired.
        /// </summary>
        public static string security_token_invalid {
            get {
                return ResourceManager.GetString("security_token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to register users in self-service on this system.
        /// </summary>
        public static string self_registration_not_allowed {
            get {
                return ResourceManager.GetString("self_registration_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to modify user data in self-service on this system.
        /// </summary>
        public static string self_service_not_allowed {
            get {
                return ResourceManager.GetString("self_service_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sort by value is invalid.
        /// </summary>
        public static string sort_by_invalid {
            get {
                return ResourceManager.GetString("sort_by_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sort order is invalid.
        /// </summary>
        public static string sort_order_invalid {
            get {
                return ResourceManager.GetString("sort_order_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state is invalid.
        /// </summary>
        public static string state_invalid {
            get {
                return ResourceManager.GetString("state_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state is too long.
        /// </summary>
        public static string state_too_long {
            get {
                return ResourceManager.GetString("state_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subdomain is invalid.
        /// </summary>
        public static string subdomain_invalid {
            get {
                return ResourceManager.GetString("subdomain_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subdomain is missing.
        /// </summary>
        public static string subdomain_missing {
            get {
                return ResourceManager.GetString("subdomain_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subdomain is too long.
        /// </summary>
        public static string subdomain_too_long {
            get {
                return ResourceManager.GetString("subdomain_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject is invalid.
        /// </summary>
        public static string subject_invalid {
            get {
                return ResourceManager.GetString("subject_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject is missing.
        /// </summary>
        public static string subject_missing {
            get {
                return ResourceManager.GetString("subject_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject is too long.
        /// </summary>
        public static string subject_too_long {
            get {
                return ResourceManager.GetString("subject_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submission message is too long.
        /// </summary>
        public static string submission_message_too_long {
            get {
                return ResourceManager.GetString("submission_message_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support email display name is invalid.
        /// </summary>
        public static string support_email_display_name_invalid {
            get {
                return ResourceManager.GetString("support_email_display_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support email display name is too long.
        /// </summary>
        public static string support_email_display_name_too_long {
            get {
                return ResourceManager.GetString("support_email_display_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support email address is invalid.
        /// </summary>
        public static string support_email_invalid {
            get {
                return ResourceManager.GetString("support_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support email address is too long.
        /// </summary>
        public static string support_email_too_long {
            get {
                return ResourceManager.GetString("support_email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant was not found.
        /// </summary>
        public static string tenant_not_found {
            get {
                return ResourceManager.GetString("tenant_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant was modified by another user, please try again.
        /// </summary>
        public static string tenant_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("tenant_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subdomain unfortunately is already being used.
        /// </summary>
        public static string tenant_subdomain_already_used {
            get {
                return ResourceManager.GetString("tenant_subdomain_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant subdomain for this tenant is immutable.
        /// </summary>
        public static string tenant_subdomain_immutable {
            get {
                return ResourceManager.GetString("tenant_subdomain_immutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant UUID is invalid.
        /// </summary>
        public static string tenant_uuid_invalid {
            get {
                return ResourceManager.GetString("tenant_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant UUID is missing.
        /// </summary>
        public static string tenant_uuid_missing {
            get {
                return ResourceManager.GetString("tenant_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text on primary color is invalid.
        /// </summary>
        public static string text_on_primary_color_invalid {
            get {
                return ResourceManager.GetString("text_on_primary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text on secondary color is invalid.
        /// </summary>
        public static string text_on_secondary_color_invalid {
            get {
                return ResourceManager.GetString("text_on_secondary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is invalid or expired.
        /// </summary>
        public static string token_invalid_or_expired {
            get {
                return ResourceManager.GetString("token_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please only update up to 50 records at once.
        /// </summary>
        public static string too_many_update_records {
            get {
                return ResourceManager.GetString("too_many_update_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user credentials are missing.
        /// </summary>
        public static string user_credentials_missing {
            get {
                return ResourceManager.GetString("user_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This system does not support managing user detail data.
        /// </summary>
        public static string user_details_not_supported {
            get {
                return ResourceManager.GetString("user_details_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user group was not found.
        /// </summary>
        public static string user_group_not_found {
            get {
                return ResourceManager.GetString("user_group_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user group &apos;{name}&apos; was modified by another user, please try again.
        /// </summary>
        public static string user_group_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("user_group_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user group UUID is invalid.
        /// </summary>
        public static string user_group_uuid_invalid {
            get {
                return ResourceManager.GetString("user_group_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user group UUID is missing.
        /// </summary>
        public static string user_group_uuid_missing {
            get {
                return ResourceManager.GetString("user_group_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name contains invalid characters.
        /// </summary>
        public static string user_name_invalid {
            get {
                return ResourceManager.GetString("user_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is missing.
        /// </summary>
        public static string user_name_missing {
            get {
                return ResourceManager.GetString("user_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is too long.
        /// </summary>
        public static string user_name_too_long {
            get {
                return ResourceManager.GetString("user_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is no member of the user group.
        /// </summary>
        public static string user_no_member_of_user_group {
            get {
                return ResourceManager.GetString("user_no_member_of_user_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{name}&apos; was modified by another user, please try again.
        /// </summary>
        public static string user_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("user_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user UUID contains invalid characters.
        /// </summary>
        public static string user_uuid_invalid {
            get {
                return ResourceManager.GetString("user_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user UUID is missing.
        /// </summary>
        public static string user_uuid_missing {
            get {
                return ResourceManager.GetString("user_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user UUID is too long.
        /// </summary>
        public static string user_uuid_too_long {
            get {
                return ResourceManager.GetString("user_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UUID is invalid.
        /// </summary>
        public static string uuid_invalid {
            get {
                return ResourceManager.GetString("uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UUID is missing.
        /// </summary>
        public static string uuid_missing {
            get {
                return ResourceManager.GetString("uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT ID is invalid.
        /// </summary>
        public static string vat_id_invalid {
            get {
                return ResourceManager.GetString("vat_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT ID is missing.
        /// </summary>
        public static string vat_id_missing {
            get {
                return ResourceManager.GetString("vat_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT ID is too long.
        /// </summary>
        public static string vat_id_too_long {
            get {
                return ResourceManager.GetString("vat_id_too_long", resourceCulture);
            }
        }
    }
}
