//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HCore.Translations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string access_token_expired {
            get {
                return ResourceManager.GetString("access_token_expired", resourceCulture);
            }
        }
        
        public static string account_locked_out {
            get {
                return ResourceManager.GetString("account_locked_out", resourceCulture);
            }
        }
        
        public static string api_credentials_missing {
            get {
                return ResourceManager.GetString("api_credentials_missing", resourceCulture);
            }
        }
        
        public static string client_id_invalid {
            get {
                return ResourceManager.GetString("client_id_invalid", resourceCulture);
            }
        }
        
        public static string client_id_missing {
            get {
                return ResourceManager.GetString("client_id_missing", resourceCulture);
            }
        }
        
        public static string client_id_too_long {
            get {
                return ResourceManager.GetString("client_id_too_long", resourceCulture);
            }
        }
        
        public static string client_secret_invalid {
            get {
                return ResourceManager.GetString("client_secret_invalid", resourceCulture);
            }
        }
        
        public static string client_secret_missing {
            get {
                return ResourceManager.GetString("client_secret_missing", resourceCulture);
            }
        }
        
        public static string client_secret_too_long {
            get {
                return ResourceManager.GetString("client_secret_too_long", resourceCulture);
            }
        }
        
        public static string code_invalid {
            get {
                return ResourceManager.GetString("code_invalid", resourceCulture);
            }
        }
        
        public static string code_missing {
            get {
                return ResourceManager.GetString("code_missing", resourceCulture);
            }
        }
        
        public static string code_too_long {
            get {
                return ResourceManager.GetString("code_too_long", resourceCulture);
            }
        }
        
        public static string duplicate_user_name {
            get {
                return ResourceManager.GetString("duplicate_user_name", resourceCulture);
            }
        }
        
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        public static string email_missing {
            get {
                return ResourceManager.GetString("email_missing", resourceCulture);
            }
        }
        
        public static string email_too_long {
            get {
                return ResourceManager.GetString("email_too_long", resourceCulture);
            }
        }
        
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        public static string issuer_invalid {
            get {
                return ResourceManager.GetString("issuer_invalid", resourceCulture);
            }
        }
        
        public static string issuer_missing {
            get {
                return ResourceManager.GetString("issuer_missing", resourceCulture);
            }
        }
        
        public static string issuer_too_long {
            get {
                return ResourceManager.GetString("issuer_too_long", resourceCulture);
            }
        }
        
        public static string max_paging_limit_exceeded {
            get {
                return ResourceManager.GetString("max_paging_limit_exceeded", resourceCulture);
            }
        }
        
        public static string max_paging_offset_exceeded {
            get {
                return ResourceManager.GetString("max_paging_offset_exceeded", resourceCulture);
            }
        }
        
        public static string name_invalid {
            get {
                return ResourceManager.GetString("name_invalid", resourceCulture);
            }
        }
        
        public static string name_missing {
            get {
                return ResourceManager.GetString("name_missing", resourceCulture);
            }
        }
        
        public static string name_too_long {
            get {
                return ResourceManager.GetString("name_too_long", resourceCulture);
            }
        }
        
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        public static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        public static string no_records_specified {
            get {
                return ResourceManager.GetString("no_records_specified", resourceCulture);
            }
        }
        
        public static string paging_limit_invalid {
            get {
                return ResourceManager.GetString("paging_limit_invalid", resourceCulture);
            }
        }
        
        public static string paging_offset_invalid {
            get {
                return ResourceManager.GetString("paging_offset_invalid", resourceCulture);
            }
        }
        
        public static string password_confirmation_missing {
            get {
                return ResourceManager.GetString("password_confirmation_missing", resourceCulture);
            }
        }
        
        public static string password_confirmation_no_match {
            get {
                return ResourceManager.GetString("password_confirmation_no_match", resourceCulture);
            }
        }
        
        public static string password_does_not_match {
            get {
                return ResourceManager.GetString("password_does_not_match", resourceCulture);
            }
        }
        
        public static string password_missing {
            get {
                return ResourceManager.GetString("password_missing", resourceCulture);
            }
        }
        
        public static string password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        public static string password_too_long {
            get {
                return ResourceManager.GetString("password_too_long", resourceCulture);
            }
        }
        
        public static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        public static string permission_denied {
            get {
                return ResourceManager.GetString("permission_denied", resourceCulture);
            }
        }
        
        public static string phone_number_invalid {
            get {
                return ResourceManager.GetString("phone_number_invalid", resourceCulture);
            }
        }
        
        public static string phone_number_missing {
            get {
                return ResourceManager.GetString("phone_number_missing", resourceCulture);
            }
        }
        
        public static string phone_number_too_long {
            get {
                return ResourceManager.GetString("phone_number_too_long", resourceCulture);
            }
        }
        
        public static string private_key_invalid {
            get {
                return ResourceManager.GetString("private_key_invalid", resourceCulture);
            }
        }
        
        public static string private_key_missing {
            get {
                return ResourceManager.GetString("private_key_missing", resourceCulture);
            }
        }
        
        public static string private_key_no_delimiters {
            get {
                return ResourceManager.GetString("private_key_no_delimiters", resourceCulture);
            }
        }
        
        public static string private_key_no_private_key {
            get {
                return ResourceManager.GetString("private_key_no_private_key", resourceCulture);
            }
        }
        
        public static string private_key_too_long {
            get {
                return ResourceManager.GetString("private_key_too_long", resourceCulture);
            }
        }
        
        public static string redirect_url_invalid {
            get {
                return ResourceManager.GetString("redirect_url_invalid", resourceCulture);
            }
        }
        
        public static string redirect_url_missing {
            get {
                return ResourceManager.GetString("redirect_url_missing", resourceCulture);
            }
        }
        
        public static string redirect_url_must_be_absolute {
            get {
                return ResourceManager.GetString("redirect_url_must_be_absolute", resourceCulture);
            }
        }
        
        public static string redirect_url_not_required {
            get {
                return ResourceManager.GetString("redirect_url_not_required", resourceCulture);
            }
        }
        
        public static string redirect_url_too_long {
            get {
                return ResourceManager.GetString("redirect_url_too_long", resourceCulture);
            }
        }
        
        public static string security_token_invalid {
            get {
                return ResourceManager.GetString("security_token_invalid", resourceCulture);
            }
        }
        
        public static string state_invalid {
            get {
                return ResourceManager.GetString("state_invalid", resourceCulture);
            }
        }
        
        public static string subject_invalid {
            get {
                return ResourceManager.GetString("subject_invalid", resourceCulture);
            }
        }
        
        public static string subject_missing {
            get {
                return ResourceManager.GetString("subject_missing", resourceCulture);
            }
        }
        
        public static string subject_too_long {
            get {
                return ResourceManager.GetString("subject_too_long", resourceCulture);
            }
        }
        
        public static string too_many_update_records {
            get {
                return ResourceManager.GetString("too_many_update_records", resourceCulture);
            }
        }
        
        public static string user_credentials_missing {
            get {
                return ResourceManager.GetString("user_credentials_missing", resourceCulture);
            }
        }
        
        public static string user_group_not_found {
            get {
                return ResourceManager.GetString("user_group_not_found", resourceCulture);
            }
        }
        
        public static string user_group_uuid_invalid {
            get {
                return ResourceManager.GetString("user_group_uuid_invalid", resourceCulture);
            }
        }
        
        public static string user_group_uuid_missing {
            get {
                return ResourceManager.GetString("user_group_uuid_missing", resourceCulture);
            }
        }
        
        public static string user_name_invalid {
            get {
                return ResourceManager.GetString("user_name_invalid", resourceCulture);
            }
        }
        
        public static string user_name_missing {
            get {
                return ResourceManager.GetString("user_name_missing", resourceCulture);
            }
        }
        
        public static string user_name_too_long {
            get {
                return ResourceManager.GetString("user_name_too_long", resourceCulture);
            }
        }
        
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        public static string user_uuid_invalid {
            get {
                return ResourceManager.GetString("user_uuid_invalid", resourceCulture);
            }
        }
        
        public static string user_uuid_missing {
            get {
                return ResourceManager.GetString("user_uuid_missing", resourceCulture);
            }
        }
        
        public static string user_uuid_too_long {
            get {
                return ResourceManager.GetString("user_uuid_too_long", resourceCulture);
            }
        }
        
        public static string uuid_invalid {
            get {
                return ResourceManager.GetString("uuid_invalid", resourceCulture);
            }
        }
        
        public static string uuid_missing {
            get {
                return ResourceManager.GetString("uuid_missing", resourceCulture);
            }
        }
        
        public static string user_details_not_supported {
            get {
                return ResourceManager.GetString("user_details_not_supported", resourceCulture);
            }
        }
        
        public static string user_no_member_of_user_group {
            get {
                return ResourceManager.GetString("user_no_member_of_user_group", resourceCulture);
            }
        }
        
        public static string scroll_uuid_invalid {
            get {
                return ResourceManager.GetString("scroll_uuid_invalid", resourceCulture);
            }
        }
        
        public static string scroll_uuid_too_long {
            get {
                return ResourceManager.GetString("scroll_uuid_too_long", resourceCulture);
            }
        }
        
        public static string argument_invalid {
            get {
                return ResourceManager.GetString("argument_invalid", resourceCulture);
            }
        }
        
        public static string argument_missing {
            get {
                return ResourceManager.GetString("argument_missing", resourceCulture);
            }
        }
        
        public static string tenant_not_found {
            get {
                return ResourceManager.GetString("tenant_not_found", resourceCulture);
            }
        }
        
        public static string authorization_authority_not_available {
            get {
                return ResourceManager.GetString("authorization_authority_not_available", resourceCulture);
            }
        }
        
        public static string token_invalid_or_expired {
            get {
                return ResourceManager.GetString("token_invalid_or_expired", resourceCulture);
            }
        }
        
        public static string cookie_invalid_or_expired {
            get {
                return ResourceManager.GetString("cookie_invalid_or_expired", resourceCulture);
            }
        }
        
        public static string first_name_invalid {
            get {
                return ResourceManager.GetString("first_name_invalid", resourceCulture);
            }
        }
        
        public static string first_name_missing {
            get {
                return ResourceManager.GetString("first_name_missing", resourceCulture);
            }
        }
        
        public static string first_name_too_long {
            get {
                return ResourceManager.GetString("first_name_too_long", resourceCulture);
            }
        }
        
        public static string last_name_invalid {
            get {
                return ResourceManager.GetString("last_name_invalid", resourceCulture);
            }
        }
        
        public static string last_name_missing {
            get {
                return ResourceManager.GetString("last_name_missing", resourceCulture);
            }
        }
        
        public static string last_name_too_long {
            get {
                return ResourceManager.GetString("last_name_too_long", resourceCulture);
            }
        }
        
        public static string self_registration_not_allowed {
            get {
                return ResourceManager.GetString("self_registration_not_allowed", resourceCulture);
            }
        }
        
        public static string self_service_not_allowed {
            get {
                return ResourceManager.GetString("self_service_not_allowed", resourceCulture);
            }
        }
        
        public static string email_not_confirmed {
            get {
                return ResourceManager.GetString("email_not_confirmed", resourceCulture);
            }
        }
        
        public static string new_password_missing {
            get {
                return ResourceManager.GetString("new_password_missing", resourceCulture);
            }
        }
        
        public static string old_password_missing {
            get {
                return ResourceManager.GetString("old_password_missing", resourceCulture);
            }
        }
        
        public static string cannot_delete_last_system_user_group_member {
            get {
                return ResourceManager.GetString("cannot_delete_last_system_user_group_member", resourceCulture);
            }
        }
        
        public static string backend_service_not_available {
            get {
                return ResourceManager.GetString("backend_service_not_available", resourceCulture);
            }
        }
        
        public static string email_already_exists {
            get {
                return ResourceManager.GetString("email_already_exists", resourceCulture);
            }
        }
        
        public static string sort_by_invalid {
            get {
                return ResourceManager.GetString("sort_by_invalid", resourceCulture);
            }
        }
        
        public static string sort_order_invalid {
            get {
                return ResourceManager.GetString("sort_order_invalid", resourceCulture);
            }
        }
        
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        public static string error_header {
            get {
                return ResourceManager.GetString("error_header", resourceCulture);
            }
        }
        
        public static string error_header_text {
            get {
                return ResourceManager.GetString("error_header_text", resourceCulture);
            }
        }
        
        public static string error_request_id {
            get {
                return ResourceManager.GetString("error_request_id", resourceCulture);
            }
        }
        
        public static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
    }
}
