//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCore.Translations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is invalid or expired ähnelt.
        /// </summary>
        public static string access_token_expired {
            get {
                return ResourceManager.GetString("access_token_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is missing ähnelt.
        /// </summary>
        public static string access_token_missing {
            get {
                return ResourceManager.GetString("access_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is too long ähnelt.
        /// </summary>
        public static string access_token_too_long {
            get {
                return ResourceManager.GetString("access_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, your user account is disabled. Please contact us for further information ähnelt.
        /// </summary>
        public static string account_disabled {
            get {
                return ResourceManager.GetString("account_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, your user account has expired. Please contact us if you want to extend the validity of your user account ähnelt.
        /// </summary>
        public static string account_expired {
            get {
                return ResourceManager.GetString("account_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation cannot be performed, because the user account is externally managed ähnelt.
        /// </summary>
        public static string account_is_externally_managed {
            get {
                return ResourceManager.GetString("account_is_externally_managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have entered a wrong password for too many times. The user account has been locked for 15 minutes due to security reasons ähnelt.
        /// </summary>
        public static string account_locked_out {
            get {
                return ResourceManager.GetString("account_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation cannot be performed, because the user groups and accounts are externally managed ähnelt.
        /// </summary>
        public static string accounts_are_externally_managed {
            get {
                return ResourceManager.GetString("accounts_are_externally_managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The address line 1 is missing ähnelt.
        /// </summary>
        public static string address_line_1_missing {
            get {
                return ResourceManager.GetString("address_line_1_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The address line 1 is too long ähnelt.
        /// </summary>
        public static string address_line_1_too_long {
            get {
                return ResourceManager.GetString("address_line_1_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The address line 2 is missing ähnelt.
        /// </summary>
        public static string address_line_2_missing {
            get {
                return ResourceManager.GetString("address_line_2_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The address line 2 is too long ähnelt.
        /// </summary>
        public static string address_line_2_too_long {
            get {
                return ResourceManager.GetString("address_line_2_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The API credentials are missing ähnelt.
        /// </summary>
        public static string api_credentials_missing {
            get {
                return ResourceManager.GetString("api_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Apple touch icon URL is missing ähnelt.
        /// </summary>
        public static string apple_touch_icon_url_missing {
            get {
                return ResourceManager.GetString("apple_touch_icon_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Apple touch icon URL is too long ähnelt.
        /// </summary>
        public static string apple_touch_icon_url_too_long {
            get {
                return ResourceManager.GetString("apple_touch_icon_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument is invalid ähnelt.
        /// </summary>
        public static string argument_invalid {
            get {
                return ResourceManager.GetString("argument_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument is missing ähnelt.
        /// </summary>
        public static string argument_missing {
            get {
                return ResourceManager.GetString("argument_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The authorization authority for this service is currently not available. Your access credentials cannot be validated. Please try again later ähnelt.
        /// </summary>
        public static string authorization_authority_not_available {
            get {
                return ResourceManager.GetString("authorization_authority_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {name} backend service is currently not available ähnelt.
        /// </summary>
        public static string backend_service_not_available {
            get {
                return ResourceManager.GetString("backend_service_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The billing type is invalid ähnelt.
        /// </summary>
        public static string billing_type_invalid {
            get {
                return ResourceManager.GetString("billing_type_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cancellation reason is missing ähnelt.
        /// </summary>
        public static string cancellation_reason_missing {
            get {
                return ResourceManager.GetString("cancellation_reason_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cancellation reason is too long ähnelt.
        /// </summary>
        public static string cancellation_reason_too_long {
            get {
                return ResourceManager.GetString("cancellation_reason_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System user groups must contain at least one member ähnelt.
        /// </summary>
        public static string cannot_delete_last_system_user_group_member {
            get {
                return ResourceManager.GetString("cannot_delete_last_system_user_group_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The city is missing ähnelt.
        /// </summary>
        public static string city_missing {
            get {
                return ResourceManager.GetString("city_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The city is too long ähnelt.
        /// </summary>
        public static string city_too_long {
            get {
                return ResourceManager.GetString("city_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user is assigned to more than 150 groups, which is not supported by Azure AD. Please either limit the amount of user groups assigned to the user, or use application roles ähnelt.
        /// </summary>
        public static string claims_principal_has_too_many_groups {
            get {
                return ResourceManager.GetString("claims_principal_has_too_many_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID contains invalid characters ähnelt.
        /// </summary>
        public static string client_id_invalid {
            get {
                return ResourceManager.GetString("client_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID is missing ähnelt.
        /// </summary>
        public static string client_id_missing {
            get {
                return ResourceManager.GetString("client_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client ID is too long ähnelt.
        /// </summary>
        public static string client_id_too_long {
            get {
                return ResourceManager.GetString("client_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret contains invalid characters ähnelt.
        /// </summary>
        public static string client_secret_invalid {
            get {
                return ResourceManager.GetString("client_secret_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret is missing ähnelt.
        /// </summary>
        public static string client_secret_missing {
            get {
                return ResourceManager.GetString("client_secret_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client secret is too long ähnelt.
        /// </summary>
        public static string client_secret_too_long {
            get {
                return ResourceManager.GetString("client_secret_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access to the file was denied ähnelt.
        /// </summary>
        public static string cloud_storage_file_access_denied {
            get {
                return ResourceManager.GetString("cloud_storage_file_access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file was not found ähnelt.
        /// </summary>
        public static string cloud_storage_file_not_found {
            get {
                return ResourceManager.GetString("cloud_storage_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code contains invalid characters ähnelt.
        /// </summary>
        public static string code_invalid {
            get {
                return ResourceManager.GetString("code_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code is missing ähnelt.
        /// </summary>
        public static string code_missing {
            get {
                return ResourceManager.GetString("code_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The code is too long ähnelt.
        /// </summary>
        public static string code_too_long {
            get {
                return ResourceManager.GetString("code_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The comment is too long ähnelt.
        /// </summary>
        public static string comment_too_long {
            get {
                return ResourceManager.GetString("comment_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The confirmation ID is missing ähnelt.
        /// </summary>
        public static string confirmation_id_missing {
            get {
                return ResourceManager.GetString("confirmation_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The confirmation ID is too long ähnelt.
        /// </summary>
        public static string confirmation_id_too_long {
            get {
                return ResourceManager.GetString("confirmation_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The contact person name is missing ähnelt.
        /// </summary>
        public static string contact_person_name_missing {
            get {
                return ResourceManager.GetString("contact_person_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The contact person name is too long ähnelt.
        /// </summary>
        public static string contact_person_name_too_long {
            get {
                return ResourceManager.GetString("contact_person_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The continuation UUID is invalid ähnelt.
        /// </summary>
        public static string continuation_uuid_invalid {
            get {
                return ResourceManager.GetString("continuation_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cookie is invalid or expired ähnelt.
        /// </summary>
        public static string cookie_invalid_or_expired {
            get {
                return ResourceManager.GetString("cookie_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language is invalid ähnelt.
        /// </summary>
        public static string culture_invalid {
            get {
                return ResourceManager.GetString("culture_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language is missing ähnelt.
        /// </summary>
        public static string culture_missing {
            get {
                return ResourceManager.GetString("culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language is too long ähnelt.
        /// </summary>
        public static string culture_too_long {
            get {
                return ResourceManager.GetString("culture_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The languages are missing ähnelt.
        /// </summary>
        public static string cultures_missing {
            get {
                return ResourceManager.GetString("cultures_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The currency is invalid ähnelt.
        /// </summary>
        public static string currency_invalid {
            get {
                return ResourceManager.GetString("currency_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The currency is missing ähnelt.
        /// </summary>
        public static string currency_missing {
            get {
                return ResourceManager.GetString("currency_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The custom CSS template is invalid: {uuid} ähnelt.
        /// </summary>
        public static string custom_css_invalid {
            get {
                return ResourceManager.GetString("custom_css_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The custom identifier is invalid ähnelt.
        /// </summary>
        public static string custom_identifier_invalid {
            get {
                return ResourceManager.GetString("custom_identifier_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The custom identifier is missing ähnelt.
        /// </summary>
        public static string custom_identifier_missing {
            get {
                return ResourceManager.GetString("custom_identifier_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The custom identifier is too long ähnelt.
        /// </summary>
        public static string custom_identifier_too_long {
            get {
                return ResourceManager.GetString("custom_identifier_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default language is missing ähnelt.
        /// </summary>
        public static string default_culture_missing {
            get {
                return ResourceManager.GetString("default_culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default currency is invalid ähnelt.
        /// </summary>
        public static string default_currency_invalid {
            get {
                return ResourceManager.GetString("default_currency_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default currency is missing ähnelt.
        /// </summary>
        public static string default_currency_missing {
            get {
                return ResourceManager.GetString("default_currency_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The description is too long ähnelt.
        /// </summary>
        public static string description_too_long {
            get {
                return ResourceManager.GetString("description_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The developer was not found ähnelt.
        /// </summary>
        public static string developer_not_found {
            get {
                return ResourceManager.GetString("developer_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This user name already exists ähnelt.
        /// </summary>
        public static string duplicate_user_name {
            get {
                return ResourceManager.GetString("duplicate_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address for this user account has already been confirmed ähnelt.
        /// </summary>
        public static string email_already_confirmed {
            get {
                return ResourceManager.GetString("email_already_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A user account with that email address already exists ähnelt.
        /// </summary>
        public static string email_already_exists {
            get {
                return ResourceManager.GetString("email_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is invalid ähnelt.
        /// </summary>
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is missing ähnelt.
        /// </summary>
        public static string email_missing {
            get {
                return ResourceManager.GetString("email_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is not yet confirmed ähnelt.
        /// </summary>
        public static string email_not_confirmed {
            get {
                return ResourceManager.GetString("email_not_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This email address does not exist ähnelt.
        /// </summary>
        public static string email_not_existing {
            get {
                return ResourceManager.GetString("email_not_existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signing up to our service with a free or low quality email address unfortunately is not possible ähnelt.
        /// </summary>
        public static string email_requires_business_account {
            get {
                return ResourceManager.GetString("email_requires_business_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email message to {uuid} unfortunately could not be send. Please make sure that the email address is valid and that your email sending settings are correct ähnelt.
        /// </summary>
        public static string email_sending_failed {
            get {
                return ResourceManager.GetString("email_sending_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address is too long ähnelt.
        /// </summary>
        public static string email_too_long {
            get {
                return ResourceManager.GetString("email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give at least one email address ähnelt.
        /// </summary>
        public static string emails_missing {
            get {
                return ResourceManager.GetString("emails_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occured ähnelt.
        /// </summary>
        public static string error_header {
            get {
                return ResourceManager.GetString("error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We are sorry, but an unexpected error occured while processing your request. ähnelt.
        /// </summary>
        public static string error_header_text {
            get {
                return ResourceManager.GetString("error_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The error message is invalid ähnelt.
        /// </summary>
        public static string error_message_is_invalid {
            get {
                return ResourceManager.GetString("error_message_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your request ID is: ähnelt.
        /// </summary>
        public static string error_request_id {
            get {
                return ResourceManager.GetString("error_request_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error ähnelt.
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please use the Single Sign On (SSO) authentication for signing in with this email address ähnelt.
        /// </summary>
        public static string external_authentication_required_for_email_domain {
            get {
                return ResourceManager.GetString("external_authentication_required_for_email_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external user group mapping contains invalid characters ähnelt.
        /// </summary>
        public static string external_user_group_identifier_invalid {
            get {
                return ResourceManager.GetString("external_user_group_identifier_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external user group mapping is too long ähnelt.
        /// </summary>
        public static string external_user_group_identifier_too_long {
            get {
                return ResourceManager.GetString("external_user_group_identifier_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external user ID is missing ähnelt.
        /// </summary>
        public static string external_user_id_is_missing {
            get {
                return ResourceManager.GetString("external_user_id_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external user was not found ähnelt.
        /// </summary>
        public static string external_user_not_found {
            get {
                return ResourceManager.GetString("external_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external UUID is too long ähnelt.
        /// </summary>
        public static string external_uuid_too_long {
            get {
                return ResourceManager.GetString("external_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The filter value is invalid ähnelt.
        /// </summary>
        public static string filter_value_invalid {
            get {
                return ResourceManager.GetString("filter_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first name contains invalid characters ähnelt.
        /// </summary>
        public static string first_name_invalid {
            get {
                return ResourceManager.GetString("first_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first name is missing ähnelt.
        /// </summary>
        public static string first_name_missing {
            get {
                return ResourceManager.GetString("first_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first name is too long ähnelt.
        /// </summary>
        public static string first_name_too_long {
            get {
                return ResourceManager.GetString("first_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The icon ICO URL is missing ähnelt.
        /// </summary>
        public static string icon_ico_url_missing {
            get {
                return ResourceManager.GetString("icon_ico_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The icon ICO URL is too long ähnelt.
        /// </summary>
        public static string icon_ico_url_too_long {
            get {
                return ResourceManager.GetString("icon_ico_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The identity token is missing ähnelt.
        /// </summary>
        public static string identity_token_missing {
            get {
                return ResourceManager.GetString("identity_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The identity token is too long ähnelt.
        /// </summary>
        public static string identity_token_too_long {
            get {
                return ResourceManager.GetString("identity_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft has ended official support for Internet Explorer 11 and older generations of Internet Explorer. For security reasons, this page therefore only works with the Microsoft Edge browser ähnelt.
        /// </summary>
        public static string ie11_and_lower_not_supported {
            get {
                return ResourceManager.GetString("ie11_and_lower_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected server error occured ähnelt.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user credentials are not valid ähnelt.
        /// </summary>
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is invalid ähnelt.
        /// </summary>
        public static string issuer_invalid {
            get {
                return ResourceManager.GetString("issuer_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is missing ähnelt.
        /// </summary>
        public static string issuer_missing {
            get {
                return ResourceManager.GetString("issuer_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The issuer is too long ähnelt.
        /// </summary>
        public static string issuer_too_long {
            get {
                return ResourceManager.GetString("issuer_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The job ID is missing ähnelt.
        /// </summary>
        public static string job_id_missing {
            get {
                return ResourceManager.GetString("job_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The job ID is too long ähnelt.
        /// </summary>
        public static string job_id_too_long {
            get {
                return ResourceManager.GetString("job_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 contains invalid characters ähnelt.
        /// </summary>
        public static string key_1_invalid {
            get {
                return ResourceManager.GetString("key_1_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 is missing ähnelt.
        /// </summary>
        public static string key_1_missing {
            get {
                return ResourceManager.GetString("key_1_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 is too long ähnelt.
        /// </summary>
        public static string key_1_too_long {
            get {
                return ResourceManager.GetString("key_1_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 contains invalid characters ähnelt.
        /// </summary>
        public static string key_2_invalid {
            get {
                return ResourceManager.GetString("key_2_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 is missing ähnelt.
        /// </summary>
        public static string key_2_missing {
            get {
                return ResourceManager.GetString("key_2_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 is too long ähnelt.
        /// </summary>
        public static string key_2_too_long {
            get {
                return ResourceManager.GetString("key_2_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 3 contains invalid characters ähnelt.
        /// </summary>
        public static string key_3_invalid {
            get {
                return ResourceManager.GetString("key_3_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 3 is missing ähnelt.
        /// </summary>
        public static string key_3_missing {
            get {
                return ResourceManager.GetString("key_3_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 3 is too long ähnelt.
        /// </summary>
        public static string key_3_too_long {
            get {
                return ResourceManager.GetString("key_3_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 4 contains invalid characters ähnelt.
        /// </summary>
        public static string key_4_invalid {
            get {
                return ResourceManager.GetString("key_4_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 4 is missing ähnelt.
        /// </summary>
        public static string key_4_missing {
            get {
                return ResourceManager.GetString("key_4_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 4 is too long ähnelt.
        /// </summary>
        public static string key_4_too_long {
            get {
                return ResourceManager.GetString("key_4_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last name contains invalid characters ähnelt.
        /// </summary>
        public static string last_name_invalid {
            get {
                return ResourceManager.GetString("last_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last name is missing ähnelt.
        /// </summary>
        public static string last_name_missing {
            get {
                return ResourceManager.GetString("last_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last name is too long ähnelt.
        /// </summary>
        public static string last_name_too_long {
            get {
                return ResourceManager.GetString("last_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last updated at from value is invalid ähnelt.
        /// </summary>
        public static string last_updated_at_from_invalid {
            get {
                return ResourceManager.GetString("last_updated_at_from_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last updated at to date is set to a date before the last updated at date ähnelt.
        /// </summary>
        public static string last_updated_at_to_before_last_updated_at_from {
            get {
                return ResourceManager.GetString("last_updated_at_to_before_last_updated_at_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last updated at to value is invalid ähnelt.
        /// </summary>
        public static string last_updated_at_to_invalid {
            get {
                return ResourceManager.GetString("last_updated_at_to_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The link is expired or invalid ähnelt.
        /// </summary>
        public static string link_invalid {
            get {
                return ResourceManager.GetString("link_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The logo PNG URL is missing ähnelt.
        /// </summary>
        public static string logo_png_url_missing {
            get {
                return ResourceManager.GetString("logo_png_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The logo PNG URL is too long ähnelt.
        /// </summary>
        public static string logo_png_url_too_long {
            get {
                return ResourceManager.GetString("logo_png_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The logo SVG URL is missing ähnelt.
        /// </summary>
        public static string logo_svg_url_missing {
            get {
                return ResourceManager.GetString("logo_svg_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The logo SVG URL is too long ähnelt.
        /// </summary>
        public static string logo_svg_url_too_long {
            get {
                return ResourceManager.GetString("logo_svg_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We are currently conducting a scheduled system maintenance. Please try again in an hour ähnelt.
        /// </summary>
        public static string maintenance_mode {
            get {
                return ResourceManager.GetString("maintenance_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging limit must not exceed 50 records ähnelt.
        /// </summary>
        public static string max_paging_limit_exceeded {
            get {
                return ResourceManager.GetString("max_paging_limit_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging offset must not exceed 5000 records ähnelt.
        /// </summary>
        public static string max_paging_offset_exceeded {
            get {
                return ResourceManager.GetString("max_paging_offset_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name contains invalid characters ähnelt.
        /// </summary>
        public static string name_invalid {
            get {
                return ResourceManager.GetString("name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name is missing ähnelt.
        /// </summary>
        public static string name_missing {
            get {
                return ResourceManager.GetString("name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name is too long ähnelt.
        /// </summary>
        public static string name_too_long {
            get {
                return ResourceManager.GetString("name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new password is missing ähnelt.
        /// </summary>
        public static string new_password_missing {
            get {
                return ResourceManager.GetString("new_password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signing up to our service with an disposable email address unfortunately is not possible ähnelt.
        /// </summary>
        public static string no_disposable_emails_allowed {
            get {
                return ResourceManager.GetString("no_disposable_emails_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide records for the update operation ähnelt.
        /// </summary>
        public static string no_records_specified {
            get {
                return ResourceManager.GetString("no_records_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The generic email display name is invalid ähnelt.
        /// </summary>
        public static string noreply_email_display_name_invalid {
            get {
                return ResourceManager.GetString("noreply_email_display_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The generic email display name is too long ähnelt.
        /// </summary>
        public static string noreply_email_display_name_too_long {
            get {
                return ResourceManager.GetString("noreply_email_display_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The generic reply email address is invalid ähnelt.
        /// </summary>
        public static string noreply_email_invalid {
            get {
                return ResourceManager.GetString("noreply_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The generic reply email address is too long ähnelt.
        /// </summary>
        public static string noreply_email_too_long {
            get {
                return ResourceManager.GetString("noreply_email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The record was not found ähnelt.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This functionality is not yet implemented ähnelt.
        /// </summary>
        public static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The notification culture is invalid ähnelt.
        /// </summary>
        public static string notification_culture_invalid {
            get {
                return ResourceManager.GetString("notification_culture_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The notification language is missing ähnelt.
        /// </summary>
        public static string notification_culture_missing {
            get {
                return ResourceManager.GetString("notification_culture_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The notification UUID is invalid ähnelt.
        /// </summary>
        public static string notification_uuid_invalid {
            get {
                return ResourceManager.GetString("notification_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The notification UUID is missing ähnelt.
        /// </summary>
        public static string notification_uuid_missing {
            get {
                return ResourceManager.GetString("notification_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The old password is missing ähnelt.
        /// </summary>
        public static string old_password_missing {
            get {
                return ResourceManager.GetString("old_password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The element was modified by another user, please try again ähnelt.
        /// </summary>
        public static string optimistic_lock_violated {
            get {
                return ResourceManager.GetString("optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The purchase order ID is missing ähnelt.
        /// </summary>
        public static string order_id_missing {
            get {
                return ResourceManager.GetString("order_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The purchase order ID is too long ähnelt.
        /// </summary>
        public static string order_id_too_long {
            get {
                return ResourceManager.GetString("order_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The company name is invalid ähnelt.
        /// </summary>
        public static string organization_invalid {
            get {
                return ResourceManager.GetString("organization_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The company name is missing ähnelt.
        /// </summary>
        public static string organization_missing {
            get {
                return ResourceManager.GetString("organization_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The company name is too long ähnelt.
        /// </summary>
        public static string organization_too_long {
            get {
                return ResourceManager.GetString("organization_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page ähnelt.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The page was not found ähnelt.
        /// </summary>
        public static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging limit must be equal to or greater than zero ähnelt.
        /// </summary>
        public static string paging_limit_invalid {
            get {
                return ResourceManager.GetString("paging_limit_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The paging offset must be equal to or greater than zero ähnelt.
        /// </summary>
        public static string paging_offset_invalid {
            get {
                return ResourceManager.GetString("paging_offset_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password confirmation is missing ähnelt.
        /// </summary>
        public static string password_confirmation_missing {
            get {
                return ResourceManager.GetString("password_confirmation_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password confirmation is not matching the password ähnelt.
        /// </summary>
        public static string password_confirmation_no_match {
            get {
                return ResourceManager.GetString("password_confirmation_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password does not match our records ähnelt.
        /// </summary>
        public static string password_does_not_match {
            get {
                return ResourceManager.GetString("password_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is missing ähnelt.
        /// </summary>
        public static string password_missing {
            get {
                return ResourceManager.GetString("password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give a safe password:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;minimum length of 10 characters&lt;/li&gt;&lt;li&gt;at least one lower case character&lt;/li&gt;&lt;li&gt;at least one upper case character&lt;/li&gt;&lt;li&gt;at least one digit&lt;/li&gt;&lt;li&gt;at least one special character&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string password_requires_digit {
            get {
                return ResourceManager.GetString("password_requires_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give a safe password:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;minimum length of 10 characters&lt;/li&gt;&lt;li&gt;at least one lower case character&lt;/li&gt;&lt;li&gt;at least one upper case character&lt;/li&gt;&lt;li&gt;at least one digit&lt;/li&gt;&lt;li&gt;at least one special character&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string password_requires_lower {
            get {
                return ResourceManager.GetString("password_requires_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give a safe password:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;minimum length of 10 characters&lt;/li&gt;&lt;li&gt;at least one lower case character&lt;/li&gt;&lt;li&gt;at least one upper case character&lt;/li&gt;&lt;li&gt;at least one digit&lt;/li&gt;&lt;li&gt;at least one special character&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give a safe password:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;minimum length of 10 characters&lt;/li&gt;&lt;li&gt;at least one lower case character&lt;/li&gt;&lt;li&gt;at least one upper case character&lt;/li&gt;&lt;li&gt;at least one digit&lt;/li&gt;&lt;li&gt;at least one special character&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string password_requires_upper {
            get {
                return ResourceManager.GetString("password_requires_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is too long ähnelt.
        /// </summary>
        public static string password_too_long {
            get {
                return ResourceManager.GetString("password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please give a safe password:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;minimum length of 10 characters&lt;/li&gt;&lt;li&gt;at least one lower case character&lt;/li&gt;&lt;li&gt;at least one upper case character&lt;/li&gt;&lt;li&gt;at least one digit&lt;/li&gt;&lt;li&gt;at least one special character&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The permission to access this location was denied ähnelt.
        /// </summary>
        public static string permission_denied {
            get {
                return ResourceManager.GetString("permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The phone number is invalid ähnelt.
        /// </summary>
        public static string phone_number_invalid {
            get {
                return ResourceManager.GetString("phone_number_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The phone number is missing ähnelt.
        /// </summary>
        public static string phone_number_missing {
            get {
                return ResourceManager.GetString("phone_number_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The phone number is too long ähnelt.
        /// </summary>
        public static string phone_number_too_long {
            get {
                return ResourceManager.GetString("phone_number_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please accept our Privacy Policy ähnelt.
        /// </summary>
        public static string please_accept_privacy_policy {
            get {
                return ResourceManager.GetString("please_accept_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please accept our Terms and Conditions ähnelt.
        /// </summary>
        public static string please_accept_terms_and_conditions {
            get {
                return ResourceManager.GetString("please_accept_terms_and_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The external login system has indicated that your email address is not yet confirmed. Please confirm your email address in your external login system before using this service ähnelt.
        /// </summary>
        public static string please_confirm_email_external {
            get {
                return ResourceManager.GetString("please_confirm_email_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The postal code is missing ähnelt.
        /// </summary>
        public static string postal_code_missing {
            get {
                return ResourceManager.GetString("postal_code_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The postal code is too long ähnelt.
        /// </summary>
        public static string postal_code_too_long {
            get {
                return ResourceManager.GetString("postal_code_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The primary color is invalid ähnelt.
        /// </summary>
        public static string primary_color_invalid {
            get {
                return ResourceManager.GetString("primary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is invalid, decoding failed ähnelt.
        /// </summary>
        public static string private_key_invalid {
            get {
                return ResourceManager.GetString("private_key_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is missing ähnelt.
        /// </summary>
        public static string private_key_missing {
            get {
                return ResourceManager.GetString("private_key_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key string contains no private key delimiters ähnelt.
        /// </summary>
        public static string private_key_no_delimiters {
            get {
                return ResourceManager.GetString("private_key_no_delimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key data given does not contain private key data ähnelt.
        /// </summary>
        public static string private_key_no_private_key {
            get {
                return ResourceManager.GetString("private_key_no_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key is too long ähnelt.
        /// </summary>
        public static string private_key_too_long {
            get {
                return ResourceManager.GetString("private_key_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, Google reCAPTCHA failed to validate that you are no robot ähnelt.
        /// </summary>
        public static string recaptcha_validation_failed {
            get {
                return ResourceManager.GetString("recaptcha_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is invalid ähnelt.
        /// </summary>
        public static string redirect_url_invalid {
            get {
                return ResourceManager.GetString("redirect_url_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is missing ähnelt.
        /// </summary>
        public static string redirect_url_missing {
            get {
                return ResourceManager.GetString("redirect_url_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL must be absolute ähnelt.
        /// </summary>
        public static string redirect_url_must_be_absolute {
            get {
                return ResourceManager.GetString("redirect_url_must_be_absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is not required ähnelt.
        /// </summary>
        public static string redirect_url_not_required {
            get {
                return ResourceManager.GetString("redirect_url_not_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The redirect URL is too long ähnelt.
        /// </summary>
        public static string redirect_url_too_long {
            get {
                return ResourceManager.GetString("redirect_url_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The refresh token is missing ähnelt.
        /// </summary>
        public static string refresh_token_missing {
            get {
                return ResourceManager.GetString("refresh_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The refresh token is too long ähnelt.
        /// </summary>
        public static string refresh_token_too_long {
            get {
                return ResourceManager.GetString("refresh_token_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rejection reason is too long ähnelt.
        /// </summary>
        public static string rejection_reason_too_long {
            get {
                return ResourceManager.GetString("rejection_reason_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scoped tenant UUID is invalid ähnelt.
        /// </summary>
        public static string scoped_tenant_uuid_invalid {
            get {
                return ResourceManager.GetString("scoped_tenant_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scoped tenant UUID is missing ähnelt.
        /// </summary>
        public static string scoped_tenant_uuid_missing {
            get {
                return ResourceManager.GetString("scoped_tenant_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scroll UUID contains invalid characters ähnelt.
        /// </summary>
        public static string scroll_uuid_invalid {
            get {
                return ResourceManager.GetString("scroll_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scroll UUID is too long ähnelt.
        /// </summary>
        public static string scroll_uuid_too_long {
            get {
                return ResourceManager.GetString("scroll_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The search term is invalid ähnelt.
        /// </summary>
        public static string search_term_invalid {
            get {
                return ResourceManager.GetString("search_term_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The search term is too long ähnelt.
        /// </summary>
        public static string search_term_loo_long {
            get {
                return ResourceManager.GetString("search_term_loo_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The search term is missing ähnelt.
        /// </summary>
        public static string search_term_missing {
            get {
                return ResourceManager.GetString("search_term_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The secondary color is invalid ähnelt.
        /// </summary>
        public static string secondary_color_invalid {
            get {
                return ResourceManager.GetString("secondary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The security token is invalid or expired ähnelt.
        /// </summary>
        public static string security_token_invalid {
            get {
                return ResourceManager.GetString("security_token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is not allowed to register users in self-service on this system ähnelt.
        /// </summary>
        public static string self_registration_not_allowed {
            get {
                return ResourceManager.GetString("self_registration_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is not allowed to modify user data in self-service on this system ähnelt.
        /// </summary>
        public static string self_service_not_allowed {
            get {
                return ResourceManager.GetString("self_service_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sort by value is invalid ähnelt.
        /// </summary>
        public static string sort_by_invalid {
            get {
                return ResourceManager.GetString("sort_by_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sort order is invalid ähnelt.
        /// </summary>
        public static string sort_order_invalid {
            get {
                return ResourceManager.GetString("sort_order_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sender verification for email address {uuid} has not yet been finalized. You need to get in touch with support@smint.io to finalize the sender verification before you can proceed ähnelt.
        /// </summary>
        public static string spf_dkim_setup_not_finalized {
            get {
                return ResourceManager.GetString("spf_dkim_setup_not_finalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state is invalid ähnelt.
        /// </summary>
        public static string state_invalid {
            get {
                return ResourceManager.GetString("state_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state is too long ähnelt.
        /// </summary>
        public static string state_too_long {
            get {
                return ResourceManager.GetString("state_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subdomain is invalid ähnelt.
        /// </summary>
        public static string subdomain_invalid {
            get {
                return ResourceManager.GetString("subdomain_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subdomain is missing ähnelt.
        /// </summary>
        public static string subdomain_missing {
            get {
                return ResourceManager.GetString("subdomain_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subdomain is too long ähnelt.
        /// </summary>
        public static string subdomain_too_long {
            get {
                return ResourceManager.GetString("subdomain_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is invalid ähnelt.
        /// </summary>
        public static string subject_invalid {
            get {
                return ResourceManager.GetString("subject_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is missing ähnelt.
        /// </summary>
        public static string subject_missing {
            get {
                return ResourceManager.GetString("subject_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subject is too long ähnelt.
        /// </summary>
        public static string subject_too_long {
            get {
                return ResourceManager.GetString("subject_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The submission message is too long ähnelt.
        /// </summary>
        public static string submission_message_too_long {
            get {
                return ResourceManager.GetString("submission_message_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support email display name is invalid ähnelt.
        /// </summary>
        public static string support_email_display_name_invalid {
            get {
                return ResourceManager.GetString("support_email_display_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support email display name is too long ähnelt.
        /// </summary>
        public static string support_email_display_name_too_long {
            get {
                return ResourceManager.GetString("support_email_display_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support email address is invalid ähnelt.
        /// </summary>
        public static string support_email_invalid {
            get {
                return ResourceManager.GetString("support_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support email address is too long ähnelt.
        /// </summary>
        public static string support_email_too_long {
            get {
                return ResourceManager.GetString("support_email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support reply email address is invalid ähnelt.
        /// </summary>
        public static string support_reply_to_email_invalid {
            get {
                return ResourceManager.GetString("support_reply_to_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The support reply email address is too long ähnelt.
        /// </summary>
        public static string support_reply_to_email_too_long {
            get {
                return ResourceManager.GetString("support_reply_to_email_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant was not found ähnelt.
        /// </summary>
        public static string tenant_not_found {
            get {
                return ResourceManager.GetString("tenant_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant was modified by another user, please try again ähnelt.
        /// </summary>
        public static string tenant_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("tenant_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This subdomain unfortunately is already being used ähnelt.
        /// </summary>
        public static string tenant_subdomain_already_used {
            get {
                return ResourceManager.GetString("tenant_subdomain_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant subdomain for this tenant is immutable ähnelt.
        /// </summary>
        public static string tenant_subdomain_immutable {
            get {
                return ResourceManager.GetString("tenant_subdomain_immutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant UUID is invalid ähnelt.
        /// </summary>
        public static string tenant_uuid_invalid {
            get {
                return ResourceManager.GetString("tenant_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tenant UUID is missing ähnelt.
        /// </summary>
        public static string tenant_uuid_missing {
            get {
                return ResourceManager.GetString("tenant_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The text on primary color is invalid ähnelt.
        /// </summary>
        public static string text_on_primary_color_invalid {
            get {
                return ResourceManager.GetString("text_on_primary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The text on secondary color is invalid ähnelt.
        /// </summary>
        public static string text_on_secondary_color_invalid {
            get {
                return ResourceManager.GetString("text_on_secondary_color_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The access token is invalid or expired ähnelt.
        /// </summary>
        public static string token_invalid_or_expired {
            get {
                return ResourceManager.GetString("token_invalid_or_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please only update up to 50 records at once ähnelt.
        /// </summary>
        public static string too_many_update_records {
            get {
                return ResourceManager.GetString("too_many_update_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The invitation message cannot be sent, because the user already signed up in the meanwhile ähnelt.
        /// </summary>
        public static string user_already_registered {
            get {
                return ResourceManager.GetString("user_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user credentials are missing ähnelt.
        /// </summary>
        public static string user_credentials_missing {
            get {
                return ResourceManager.GetString("user_credentials_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This system does not support managing user detail data ähnelt.
        /// </summary>
        public static string user_details_not_supported {
            get {
                return ResourceManager.GetString("user_details_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group was not found ähnelt.
        /// </summary>
        public static string user_group_not_found {
            get {
                return ResourceManager.GetString("user_group_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group &apos;{name}&apos; was modified by another user, please try again ähnelt.
        /// </summary>
        public static string user_group_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("user_group_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group UUID is invalid ähnelt.
        /// </summary>
        public static string user_group_uuid_invalid {
            get {
                return ResourceManager.GetString("user_group_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user group UUID is missing ähnelt.
        /// </summary>
        public static string user_group_uuid_missing {
            get {
                return ResourceManager.GetString("user_group_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name contains invalid characters ähnelt.
        /// </summary>
        public static string user_name_invalid {
            get {
                return ResourceManager.GetString("user_name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name is missing ähnelt.
        /// </summary>
        public static string user_name_missing {
            get {
                return ResourceManager.GetString("user_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name is too long ähnelt.
        /// </summary>
        public static string user_name_too_long {
            get {
                return ResourceManager.GetString("user_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user is no member of the user group ähnelt.
        /// </summary>
        public static string user_no_member_of_user_group {
            get {
                return ResourceManager.GetString("user_no_member_of_user_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user was not found ähnelt.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user &apos;{name}&apos; was modified by another user, please try again ähnelt.
        /// </summary>
        public static string user_optimistic_lock_violated {
            get {
                return ResourceManager.GetString("user_optimistic_lock_violated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user UUID contains invalid characters ähnelt.
        /// </summary>
        public static string user_uuid_invalid {
            get {
                return ResourceManager.GetString("user_uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user UUID is missing ähnelt.
        /// </summary>
        public static string user_uuid_missing {
            get {
                return ResourceManager.GetString("user_uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user UUID is too long ähnelt.
        /// </summary>
        public static string user_uuid_too_long {
            get {
                return ResourceManager.GetString("user_uuid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UUID is invalid ähnelt.
        /// </summary>
        public static string uuid_invalid {
            get {
                return ResourceManager.GetString("uuid_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UUID is missing ähnelt.
        /// </summary>
        public static string uuid_missing {
            get {
                return ResourceManager.GetString("uuid_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately the validation failed ähnelt.
        /// </summary>
        public static string validation_failed {
            get {
                return ResourceManager.GetString("validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The VAT ID is invalid ähnelt.
        /// </summary>
        public static string vat_id_invalid {
            get {
                return ResourceManager.GetString("vat_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The VAT ID is missing ähnelt.
        /// </summary>
        public static string vat_id_missing {
            get {
                return ResourceManager.GetString("vat_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The VAT ID is too long ähnelt.
        /// </summary>
        public static string vat_id_too_long {
            get {
                return ResourceManager.GetString("vat_id_too_long", resourceCulture);
            }
        }
    }
}
