//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCore.Identity.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I consent to receive email communications about {0} products and business in accordance with the &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;. I understand that I can unsubscribe at any time. ähnelt.
        /// </summary>
        public static string accept_communication {
            get {
                return ResourceManager.GetString("accept_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string accept_privacy_policy {
            get {
                return ResourceManager.GetString("accept_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Terms and Conditions&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string accept_terms_and_conditions {
            get {
                return ResourceManager.GetString("accept_terms_and_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Terms and Conditions&lt;/a&gt; and the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{2}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string accept_terms_and_conditions_and_privacy_policy {
            get {
                return ResourceManager.GetString("accept_terms_and_conditions_and_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept updated terms ähnelt.
        /// </summary>
        public static string accept_terms_title {
            get {
                return ResourceManager.GetString("accept_terms_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access denied ähnelt.
        /// </summary>
        public static string access_to_page_denied_header {
            get {
                return ResourceManager.GetString("access_to_page_denied_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but you do not have permissions to view this page. ähnelt.
        /// </summary>
        public static string access_to_page_denied_header_text {
            get {
                return ResourceManager.GetString("access_to_page_denied_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access denied ähnelt.
        /// </summary>
        public static string access_to_page_denied_title {
            get {
                return ResourceManager.GetString("access_to_page_denied_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create user account ähnelt.
        /// </summary>
        public static string button_create_user_account {
            get {
                return ResourceManager.GetString("button_create_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string button_log_out {
            get {
                return ResourceManager.GetString("button_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string button_register {
            get {
                return ResourceManager.GetString("button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset password ähnelt.
        /// </summary>
        public static string button_reset_password {
            get {
                return ResourceManager.GetString("button_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string button_sign_in {
            get {
                return ResourceManager.GetString("button_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string button_submit {
            get {
                return ResourceManager.GetString("button_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        public static string change_password_button_text {
            get {
                return ResourceManager.GetString("change_password_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can not change your password here, because your user account is externally managed. Please talk to your system administrator for more information. ähnelt.
        /// </summary>
        public static string change_password_not_possible {
            get {
                return ResourceManager.GetString("change_password_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        public static string change_password_title {
            get {
                return ResourceManager.GetString("change_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email address verified ähnelt.
        /// </summary>
        public static string confirm_email_header {
            get {
                return ResourceManager.GetString("confirm_email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You successfully verified your email address. Thank you very much! ähnelt.
        /// </summary>
        public static string confirm_email_header_text {
            get {
                return ResourceManager.GetString("confirm_email_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die click here to log in ähnelt.
        /// </summary>
        public static string confirm_email_header_text_link {
            get {
                return ResourceManager.GetString("confirm_email_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please ähnelt.
        /// </summary>
        public static string confirm_email_header_text_prefix {
            get {
                return ResourceManager.GetString("confirm_email_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die . ähnelt.
        /// </summary>
        public static string confirm_email_header_text_suffix {
            get {
                return ResourceManager.GetString("confirm_email_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email address verified ähnelt.
        /// </summary>
        public static string confirm_email_title {
            get {
                return ResourceManager.GetString("confirm_email_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom identifier ähnelt.
        /// </summary>
        public static string custom_identifier {
            get {
                return ResourceManager.GetString("custom_identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die . ähnelt.
        /// </summary>
        public static string email_confirmation_send_header_text_suffix {
            get {
                return ResourceManager.GetString("email_confirmation_send_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The verification email was sent ähnelt.
        /// </summary>
        public static string email_confirmation_sent_header {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check your email inbox to verify your email address. ähnelt.
        /// </summary>
        public static string email_confirmation_sent_header_text {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die please click here to log in ähnelt.
        /// </summary>
        public static string email_confirmation_sent_header_text_link {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Then ähnelt.
        /// </summary>
        public static string email_confirmation_sent_header_text_prefix {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verification email sent ähnelt.
        /// </summary>
        public static string email_confirmation_sent_title {
            get {
                return ResourceManager.GetString("email_confirmation_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resend verification email ähnelt.
        /// </summary>
        public static string email_not_confirmed_button_resend {
            get {
                return ResourceManager.GetString("email_not_confirmed_button_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please verify your email address ähnelt.
        /// </summary>
        public static string email_not_confirmed_header {
            get {
                return ResourceManager.GetString("email_not_confirmed_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We sent a verification email message to your email address. Please check your email inbox and click the link in the message to verify your email address. ähnelt.
        /// </summary>
        public static string email_not_confirmed_header_text {
            get {
                return ResourceManager.GetString("email_not_confirmed_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify your email address ähnelt.
        /// </summary>
        public static string email_not_confirmed_title {
            get {
                return ResourceManager.GetString("email_not_confirmed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name ähnelt.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password reset email was sent ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_header {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We sent a password reset email message to your email address. Please check your email inbox and click the link in the message to reset your password. ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_header_text {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die click here to log in ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_header_text_link {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can also ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_header_text_prefix {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die . ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_header_text_suffix {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password reset email sent ähnelt.
        /// </summary>
        public static string forgot_password_confirmation_title {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did you forget your password? ähnelt.
        /// </summary>
        public static string forgot_password_header {
            get {
                return ResourceManager.GetString("forgot_password_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No problem, we can send a link to your email address which you can use to reset your password. Please just enter your email address below. ähnelt.
        /// </summary>
        public static string forgot_password_header_text {
            get {
                return ResourceManager.GetString("forgot_password_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot password ähnelt.
        /// </summary>
        public static string forgot_password_title {
            get {
                return ResourceManager.GetString("forgot_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group notifications ähnelt.
        /// </summary>
        public static string group_notifications {
            get {
                return ResourceManager.GetString("group_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only receive notifications for myself ähnelt.
        /// </summary>
        public static string group_notifications_off {
            get {
                return ResourceManager.GetString("group_notifications_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also receive group notifications ähnelt.
        /// </summary>
        public static string group_notifications_on {
            get {
                return ResourceManager.GetString("group_notifications_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name ähnelt.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are now logged out ähnelt.
        /// </summary>
        public static string log_out_confirmed_header {
            get {
                return ResourceManager.GetString("log_out_confirmed_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We hope to see you back again soon! ähnelt.
        /// </summary>
        public static string log_out_confirmed_header_text {
            get {
                return ResourceManager.GetString("log_out_confirmed_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die here ähnelt.
        /// </summary>
        public static string log_out_confirmed_redirect_text_link {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click ähnelt.
        /// </summary>
        public static string log_out_confirmed_redirect_text_prefix {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to return to the main page. ähnelt.
        /// </summary>
        public static string log_out_confirmed_redirect_text_suffix {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to log out? ähnelt.
        /// </summary>
        public static string log_out_header {
            get {
                return ResourceManager.GetString("log_out_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please click the button below to confirm. ähnelt.
        /// </summary>
        public static string log_out_header_text {
            get {
                return ResourceManager.GetString("log_out_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string log_out_title {
            get {
                return ResourceManager.GetString("log_out_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage your user account ähnelt.
        /// </summary>
        public static string manage_account_header {
            get {
                return ResourceManager.GetString("manage_account_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string manage_account_password_link {
            get {
                return ResourceManager.GetString("manage_account_password_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string manage_account_profile_link {
            get {
                return ResourceManager.GetString("manage_account_profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can change your user account settings here. ähnelt.
        /// </summary>
        public static string manage_account_subheader {
            get {
                return ResourceManager.GetString("manage_account_subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string manage_notification_settings_link {
            get {
                return ResourceManager.GetString("manage_notification_settings_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password ähnelt.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm new password ähnelt.
        /// </summary>
        public static string new_password_confirmation {
            get {
                return ResourceManager.GetString("new_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification language ähnelt.
        /// </summary>
        public static string notification_culture {
            get {
                return ResourceManager.GetString("notification_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string notifications_title {
            get {
                return ResourceManager.GetString("notifications_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password ähnelt.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company name ähnelt.
        /// </summary>
        public static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        public static string password_confirmation {
            get {
                return ResourceManager.GetString("password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIN ähnelt.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resend confirmation email ähnelt.
        /// </summary>
        public static string profile_resend_verification_email_link {
            get {
                return ResourceManager.GetString("profile_resend_verification_email_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application specific data ähnelt.
        /// </summary>
        public static string proprietary_data {
            get {
                return ResourceManager.GetString("proprietary_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration ähnelt.
        /// </summary>
        public static string register_header {
            get {
                return ResourceManager.GetString("register_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register for your new user account now. ähnelt.
        /// </summary>
        public static string register_header_text {
            get {
                return ResourceManager.GetString("register_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration ähnelt.
        /// </summary>
        public static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember login ähnelt.
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password has been reset ähnelt.
        /// </summary>
        public static string reset_password_confirmation_header {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password has been reset successfully. ähnelt.
        /// </summary>
        public static string reset_password_confirmation_header_text {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die click here to log in ähnelt.
        /// </summary>
        public static string reset_password_confirmation_header_text_link {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please ähnelt.
        /// </summary>
        public static string reset_password_confirmation_header_text_prefix {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die . ähnelt.
        /// </summary>
        public static string reset_password_confirmation_header_text_suffix {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password reset ähnelt.
        /// </summary>
        public static string reset_password_confirmation_title {
            get {
                return ResourceManager.GetString("reset_password_confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset your password ähnelt.
        /// </summary>
        public static string reset_password_header {
            get {
                return ResourceManager.GetString("reset_password_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset password ähnelt.
        /// </summary>
        public static string reset_password_title {
            get {
                return ResourceManager.GetString("reset_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produkt auswählen ähnelt.
        /// </summary>
        public static string select_product_title {
            get {
                return ResourceManager.GetString("select_product_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you already have a user account? ähnelt.
        /// </summary>
        public static string sign_in_button_already_have_account {
            get {
                return ResourceManager.GetString("sign_in_button_already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot password? ähnelt.
        /// </summary>
        public static string sign_in_button_forgot_password {
            get {
                return ResourceManager.GetString("sign_in_button_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register new user account ähnelt.
        /// </summary>
        public static string sign_in_button_register {
            get {
                return ResourceManager.GetString("sign_in_button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string sign_in_header {
            get {
                return ResourceManager.GetString("sign_in_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome! Please enter your user credentials to sign in. ähnelt.
        /// </summary>
        public static string sign_in_header_text {
            get {
                return ResourceManager.GetString("sign_in_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no login schemes configured for this client. ähnelt.
        /// </summary>
        public static string sign_in_no_login_schemes_text {
            get {
                return ResourceManager.GetString("sign_in_no_login_schemes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string sign_in_title {
            get {
                return ResourceManager.GetString("sign_in_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The verification email has been sent, please check your email ähnelt.
        /// </summary>
        public static string verification_email_resent {
            get {
                return ResourceManager.GetString("verification_email_resent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password has been changed ähnelt.
        /// </summary>
        public static string your_password_has_been_changed {
            get {
                return ResourceManager.GetString("your_password_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your profile has been updated ähnelt.
        /// </summary>
        public static string your_profile_has_been_updated {
            get {
                return ResourceManager.GetString("your_profile_has_been_updated", resourceCulture);
            }
        }
    }
}
