//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCore.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCore.Identity.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I consent to receive email communications about {0} products and business in accordance with the &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;. I understand that I can unsubscribe at any time..
        /// </summary>
        public static string accept_communication {
            get {
                return ResourceManager.GetString("accept_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;..
        /// </summary>
        public static string accept_privacy_policy {
            get {
                return ResourceManager.GetString("accept_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Terms and Conditions&lt;/a&gt;..
        /// </summary>
        public static string accept_terms_and_conditions {
            get {
                return ResourceManager.GetString("accept_terms_and_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{1}&apos;);&quot;&gt;Terms and Conditions&lt;/a&gt; and the {0} &lt;a href=&quot;javascript:openUrlInNewWindow(&apos;{2}&apos;);&quot;&gt;Privacy Policy&lt;/a&gt;..
        /// </summary>
        public static string accept_terms_and_conditions_and_privacy_policy {
            get {
                return ResourceManager.GetString("accept_terms_and_conditions_and_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string access_to_page_denied_header {
            get {
                return ResourceManager.GetString("access_to_page_denied_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you do not have permissions to view this page..
        /// </summary>
        public static string access_to_page_denied_header_text {
            get {
                return ResourceManager.GetString("access_to_page_denied_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string access_to_page_denied_title {
            get {
                return ResourceManager.GetString("access_to_page_denied_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user account.
        /// </summary>
        public static string button_create_user_account {
            get {
                return ResourceManager.GetString("button_create_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string button_log_out {
            get {
                return ResourceManager.GetString("button_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string button_register {
            get {
                return ResourceManager.GetString("button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string button_reset_password {
            get {
                return ResourceManager.GetString("button_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string button_sign_in {
            get {
                return ResourceManager.GetString("button_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string button_submit {
            get {
                return ResourceManager.GetString("button_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password_button_text {
            get {
                return ResourceManager.GetString("change_password_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not change your password here, because your user account is externally managed. Please talk to your system administrator for more information..
        /// </summary>
        public static string change_password_not_possible {
            get {
                return ResourceManager.GetString("change_password_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password_title {
            get {
                return ResourceManager.GetString("change_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address verified.
        /// </summary>
        public static string confirm_email_header {
            get {
                return ResourceManager.GetString("confirm_email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully verified your email address. Thank you very much!.
        /// </summary>
        public static string confirm_email_header_text {
            get {
                return ResourceManager.GetString("confirm_email_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string confirm_email_header_text_link {
            get {
                return ResourceManager.GetString("confirm_email_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string confirm_email_header_text_prefix {
            get {
                return ResourceManager.GetString("confirm_email_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string confirm_email_header_text_suffix {
            get {
                return ResourceManager.GetString("confirm_email_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address verified.
        /// </summary>
        public static string confirm_email_title {
            get {
                return ResourceManager.GetString("confirm_email_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string email_confirmation_send_header_text_suffix {
            get {
                return ResourceManager.GetString("email_confirmation_send_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification email was sent.
        /// </summary>
        public static string email_confirmation_sent_header {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email inbox to verify your email address..
        /// </summary>
        public static string email_confirmation_sent_header_text {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please click here to log in.
        /// </summary>
        public static string email_confirmation_sent_header_text_link {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string email_confirmation_sent_header_text_prefix {
            get {
                return ResourceManager.GetString("email_confirmation_sent_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent.
        /// </summary>
        public static string email_confirmation_sent_title {
            get {
                return ResourceManager.GetString("email_confirmation_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend verification email.
        /// </summary>
        public static string email_not_confirmed_button_resend {
            get {
                return ResourceManager.GetString("email_not_confirmed_button_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address.
        /// </summary>
        public static string email_not_confirmed_header {
            get {
                return ResourceManager.GetString("email_not_confirmed_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a verification email message to your email address. Please check your email inbox and click the link in the message to verify your email address..
        /// </summary>
        public static string email_not_confirmed_header_text {
            get {
                return ResourceManager.GetString("email_not_confirmed_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email address.
        /// </summary>
        public static string email_not_confirmed_title {
            get {
                return ResourceManager.GetString("email_not_confirmed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reset email was sent.
        /// </summary>
        public static string forgot_password_confirmation_header {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a password reset email message to your email address. Please check your email inbox and click the link in the message to reset your password..
        /// </summary>
        public static string forgot_password_confirmation_header_text {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string forgot_password_confirmation_header_text_link {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also.
        /// </summary>
        public static string forgot_password_confirmation_header_text_prefix {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string forgot_password_confirmation_header_text_suffix {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email sent.
        /// </summary>
        public static string forgot_password_confirmation_title {
            get {
                return ResourceManager.GetString("forgot_password_confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your password?.
        /// </summary>
        public static string forgot_password_header {
            get {
                return ResourceManager.GetString("forgot_password_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem, we can send a link to your email address which you can use to reset your password. Please just enter your email address below..
        /// </summary>
        public static string forgot_password_header_text {
            get {
                return ResourceManager.GetString("forgot_password_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string forgot_password_title {
            get {
                return ResourceManager.GetString("forgot_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group notifications.
        /// </summary>
        public static string group_notifications {
            get {
                return ResourceManager.GetString("group_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only receive notifications for myself.
        /// </summary>
        public static string group_notifications_off {
            get {
                return ResourceManager.GetString("group_notifications_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also receive group notifications.
        /// </summary>
        public static string group_notifications_on {
            get {
                return ResourceManager.GetString("group_notifications_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out.
        /// </summary>
        public static string log_out_confirmed_header {
            get {
                return ResourceManager.GetString("log_out_confirmed_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to see you back again soon!.
        /// </summary>
        public static string log_out_confirmed_header_text {
            get {
                return ResourceManager.GetString("log_out_confirmed_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string log_out_confirmed_redirect_text_link {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string log_out_confirmed_redirect_text_prefix {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to return to the main page..
        /// </summary>
        public static string log_out_confirmed_redirect_text_suffix {
            get {
                return ResourceManager.GetString("log_out_confirmed_redirect_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to log out?.
        /// </summary>
        public static string log_out_header {
            get {
                return ResourceManager.GetString("log_out_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the button below to confirm..
        /// </summary>
        public static string log_out_header_text {
            get {
                return ResourceManager.GetString("log_out_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string log_out_title {
            get {
                return ResourceManager.GetString("log_out_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your user account.
        /// </summary>
        public static string manage_account_header {
            get {
                return ResourceManager.GetString("manage_account_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string manage_account_password_link {
            get {
                return ResourceManager.GetString("manage_account_password_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string manage_account_profile_link {
            get {
                return ResourceManager.GetString("manage_account_profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your user account settings here..
        /// </summary>
        public static string manage_account_subheader {
            get {
                return ResourceManager.GetString("manage_account_subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string manage_notification_settings_link {
            get {
                return ResourceManager.GetString("manage_notification_settings_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string new_password_confirmation {
            get {
                return ResourceManager.GetString("new_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification language.
        /// </summary>
        public static string notification_culture {
            get {
                return ResourceManager.GetString("notification_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications_title {
            get {
                return ResourceManager.GetString("notifications_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string password_confirmation {
            get {
                return ResourceManager.GetString("password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation email.
        /// </summary>
        public static string profile_resend_verification_email_link {
            get {
                return ResourceManager.GetString("profile_resend_verification_email_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string register_header {
            get {
                return ResourceManager.GetString("register_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for your new user account now..
        /// </summary>
        public static string register_header_text {
            get {
                return ResourceManager.GetString("register_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember login.
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string reset_password_confirmation_header {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string reset_password_confirmation_header_text {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string reset_password_confirmation_header_text_link {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string reset_password_confirmation_header_text_prefix {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string reset_password_confirmation_header_text_suffix {
            get {
                return ResourceManager.GetString("reset_password_confirmation_header_text_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string reset_password_confirmation_title {
            get {
                return ResourceManager.GetString("reset_password_confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string reset_password_header {
            get {
                return ResourceManager.GetString("reset_password_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password_title {
            get {
                return ResourceManager.GetString("reset_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an user account?.
        /// </summary>
        public static string sign_in_button_already_have_account {
            get {
                return ResourceManager.GetString("sign_in_button_already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string sign_in_button_forgot_password {
            get {
                return ResourceManager.GetString("sign_in_button_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user account.
        /// </summary>
        public static string sign_in_button_register {
            get {
                return ResourceManager.GetString("sign_in_button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string sign_in_header {
            get {
                return ResourceManager.GetString("sign_in_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Please enter your user credentials to sign in..
        /// </summary>
        public static string sign_in_header_text {
            get {
                return ResourceManager.GetString("sign_in_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no login schemes configured for this client..
        /// </summary>
        public static string sign_in_no_login_schemes_text {
            get {
                return ResourceManager.GetString("sign_in_no_login_schemes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string sign_in_title {
            get {
                return ResourceManager.GetString("sign_in_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification email has been sent, please check your email.
        /// </summary>
        public static string verification_email_resent {
            get {
                return ResourceManager.GetString("verification_email_resent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string your_password_has_been_changed {
            get {
                return ResourceManager.GetString("your_password_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string your_profile_has_been_updated {
            get {
                return ResourceManager.GetString("your_profile_has_been_updated", resourceCulture);
            }
        }
    }
}
