/*
 * HCore Identity Auth API
 *
 * The HCore Identity Auth API provides the most common methods to handle authentication server side using ASP.NET Identity Core.
 *
 * OpenAPI spec version: 1.0.0-s2
 * Contact: holzner@invest-fit.at
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace HCore.Identity.Models
{ 
    /// <summary>
    /// The information required to late accept the terms and conditions
    /// </summary>
    [DataContract]
    [NotMapped]
	public partial class UserAcceptTermsSpec
    { 
		public string UserUuid { get; set; }

        public bool AcceptTermsAndConditions { get; set; }

        public bool AcceptTermsAndConditionsAndPrivacyPolicy { get; set; }

        public bool AcceptPrivacyPolicy { get; set; }

        public bool AcceptCommunication { get; set; }
    }
}
