/*
 * Smint.io Portals Admin Backend API
 *
 * The Smint.io Portals Admin Backend API allows to administrate the Portals API backend 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: office@smint.io
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace HCore.Tenants.Models
{ 
        /// <summary>
        /// Currently supported billing types
        /// </summary>
        /// <value>Currently supported billing types</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SubscriptionBillingTypeEnum
        {
            
            /// <summary>
            /// Enum MonthlyInvoiceEnum for monthly_invoice
            /// </summary>
            [EnumMember(Value = "monthly_invoice")]
            MonthlyInvoiceEnum = 1-1,
            
            /// <summary>
            /// Enum YearlyInvoiceEnum for yearly_invoice
            /// </summary>
            [EnumMember(Value = "yearly_invoice")]
            YearlyInvoiceEnum = 2-1,
            
            /// <summary>
            /// Enum MonthlyAutomaticEnum for monthly_automatic
            /// </summary>
            [EnumMember(Value = "monthly_automatic")]
            MonthlyAutomaticEnum = 3-1,
            
            /// <summary>
            /// Enum YearlyAutomaticEnum for yearly_automatic
            /// </summary>
            [EnumMember(Value = "yearly_automatic")]
            YearlyAutomaticEnum = 4-1
        }
}
